### ISSUE TITLE
Add support for Tor v3 addresses

### ISSUE THREAD

**Issue by bitcoinlizard** [ElementsProject/elements#1007]
When starting with a Tor v3 address in the externalip setting I get this error:

Error: Cannot resolve -externalip address: 'TORV3ADDRESSHERE.onion'

Tor v2 is basically dead.  Support ends in October of this year.  Bitcoin Core supports Tor v3 so there should be a road map for Elements.

**Comment by apoelstra** [comment]
Thanks for the report. As you say, this is supported in Bitcoin Core and was pulled in with #935
