### ISSUE TITLE
Code on create Sidechain not justified.

### ISSUE THREAD

**Issue by Alex-Keyes** [ElementsProject/elements#102]
The code on [this page](https://elementsproject.org/sidechains/creating-your-own.html), defining the vars to create a sidechain isn't justified to be readable.  It runs completely off to the side of the page.  This can be fixed using a simple div tag or the like.

**Comment by TomMcCabe** [comment]
There's a repo for elementsproject.org:

https://github.com/ElementsProject/elementsproject.org

**Comment by Alex-Keyes** [comment]
Oh sorry I didn't know! Moving over there now...
