### ISSUE TITLE
OP_CHECKSIGVERIFY incorrectly checks for a hash type suffix of signatures

### ISSUE THREAD

**Issue by roconnor-blockstream** [ElementsProject/elements#103]
CHECKSIGFROMSTACKVERIFY calls CheckSignatureEncoding:

https://github.com/ElementsProject/elements/blob/1e20db4a79fc462439d9e92ddce1531d7be5a23e/src/script/interpreter.cpp#L1228

CheckSignatureEncoding in turns calls IsDefinedHashtypeSignature

https://github.com/ElementsProject/elements/blob/1e20db4a79fc462439d9e92ddce1531d7be5a23e/src/script/interpreter.cpp#L145

which is incorrect because signatures for CHECKSIGFROMSTACKVERIFY do not have hashtypes.

One way of fixing this could be to mask out SCRIPT_VERIFY_STRICTENC when calling CheckSignatureEncoding.

A better way would be to give signatures from CHECKSIG and CHECKSIGFROMSTACK different types.

**Comment by instagibbs** [comment]
It seems you mean CHECKSIGFROMSTACKVERIFY here, right?

**Comment by Christewart** [comment]
concept ACK on creating some sort of algebraic data type, but since types aren't interpreted until they are popped off the stack w/ the given op code in the script i'm not sure that is possible. Is there any specification on what `OP_CHECKSIGFROMSTACK` does? 

Does it verify the data one the stack hashes to the same value which we signed with the private key corresponding to the public key on the stack? What is the use case for this?

**Comment by roconnor-blockstream** [comment]
@instagibbs yes; I've corrected my comment.

**Comment by roconnor-blockstream** [comment]
@Christewart OP_CHECKSIGROMSTACK takes from the stack 
1. a pub key
2. a message (arbitrary data)
3. a signature

Then it hashes the message once with SHA256 and does an ECDSA digital signature verification with the pub key and the signature and the hashed message, and pushes the result of that verification.

**Comment by Christewart** [comment]
Another possible solution is just appending a hash type, and then replacing `pubKey.verify` with a custom function that verifies signatures similar to how [TransactionSignatureChecker.checkSig](https://github.com/ElementsProject/elements/blob/491ef45d595642022ac1e969df638b5be87cc941/src/script/interpreter.cpp#L1933-L1934) does.

**Comment by instagibbs** [comment]
I think it's a question if the "good" solution is worth the squeeze. As this problem only affects policy, by far the least disruptive change is to simply turn off the strictenc flag for that call, which literally only turns off the sighash type check.

Better solutions require monkeying around with a lot more code. I did figure a one-line change that at least lets us add the signature check to the sigcache, but that's orthogonal to this.

**Comment by Christewart** [comment]
@instagibbs This is more of a meta question, but how concerned are we about hard forking this blockchain at this early stage? Are we committed to soft forks or can we make sweeping changes that would be easier as a HF. It's not like we have PoW to worry about yet and the system is extremely centralized with 7 functionaries.

**Comment by instagibbs** [comment]
@Christewart Policy here is to not hard-fork an already-existing chain. Before starting a subsequent chain we can do any changes we like.

**Comment by instagibbs** [comment]
this should be corrected by adding an exception in the policy in the current `elements-0.13.1` codebase.

**Comment by instagibbs** [comment]
Fixed long ago.
