### ISSUE TITLE
Weight needs to be cached for OP_TXWEIGHT

### ISSUE THREAD

**Issue by roconnor-blockstream** [ElementsProject/elements#1031]
The operation `GetSerializeSize` is `O(transaction_size)` instead of `O(1)`.  Thus this value need to be cached.

https://github.com/ElementsProject/elements/commit/61b5152d445508f12155b477d77fa0940ae7fba7#diff-a0337ffd7259e8c7c9a7786d6dbd420c80abfa1afdb34ebae3261109d9ae3c19R2426-R2431

**Comment by apoelstra** [comment]
Closed by #1030
