### ISSUE TITLE
Out of date dependencies prevent building on Arch

### ISSUE THREAD

**Issue by wirion** [ElementsProject/elements#104]
When building the alpha branch, I am getting the following error:
```
net.cpp: In function ‘void ThreadMapPort()’:
net.cpp:1000:68: error: invalid conversion from ‘int*’ to ‘unsigned char’ [-fpermissive]
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
                                                                    ^~~~~~
net.cpp:1000:74: error: too few arguments to function ‘UPNPDev* upnpDiscover(int, const char*, const char*, int, int, unsigned char, int*)’
     devlist = upnpDiscover(2000, multicastif, minissdpdpath, 0, 0, &error);
```
I have miniupnpc 2.0 on my Arch system.
Sorry in advance if this is not the right place to post this.

**Comment by TomMcCabe** [comment]
Can you tell us what commands you ran to build? My concern being the Arch example builds without miniupnpc...https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md#setup-and-build-example-arch-linux

**Comment by wirion** [comment]
I was using
```
./autogen.sh && ./configure && make
```
without modifiers.

I see there was a [change in API](https://github.com/miniupnp/miniupnp/blob/1337158fcff401def996e211d5940c9f74f92b51/miniupnpc/Changelog.txt#L42-L43) from 1.9 to 2.0 which did change the [upnpDiscover](https://github.com/miniupnp/miniupnp/blob/miniupnpc_2_0/miniupnpc/miniupnpc.h#L64) function. Ubuntu seems to use miniupnpc 1.9 for the moment and Arch uses miniupnpc 2.0.

I rebuilt by adding `--without-miniupnpc` only and got past the `upnpDiscover` errors but still get errors about ambiguous operators.
```
chainparams.cpp: In constructor ‘CMainParams::CMainParams(CScript)’:
chainparams.cpp:145:51: error: ambiguous overload for ‘operator=’ (operand types are ‘std::vector<unsigned char>’ and ‘boost::assign_detail::generic_list<int>’)
         base58Prefixes[PUBKEY_ADDRESS] = list_of(0);
```
I've got boost 1.61 and I've tried to build boost 1.58 which is what is on Ubuntu's xenial xerus, but got more errors in turn.

**Comment by wirion** [comment]
Just for reference, bitcoin/bitcoin's master builds fine on my system. I see they [accounted](https://github.com/bitcoin/bitcoin/blob/6423116741de2144872389cf63a621539ae79aaa/src/net.cpp#L1345) for the new dependency. Are there plans to rebase elements off a newer bitcoin release?

**Comment by jonasnick** [comment]
Hi @wirion wirion. I'm also using Arch and I have the same problem. You can work around it by building with C++03 and fixing leveldb's build system (which was replaced upstream). 

leveldb.patch
```
diff --git a/src/leveldb/Makefile b/src/leveldb/Makefile
index 2bd2cad..50e360a 100644
--- a/src/leveldb/Makefile
+++ b/src/leveldb/Makefile
@@ -21,7 +21,7 @@ $(shell CC="$(CC)" CXX="$(CXX)" TARGET_OS="$(TARGET_OS)" \
 include build_config.mk
 
 CFLAGS += -I. -I./include $(PLATFORM_CCFLAGS) $(OPT)
-CXXFLAGS += -I. -I./include $(PLATFORM_CXXFLAGS) $(OPT)
+CXXFLAGS += -I. -I./include $(OPT) $(PLATFORM_CXXFLAGS)
 
 LDFLAGS += $(PLATFORM_LDFLAGS)
 LIBS += $(PLATFORM_LIBS)
```
Then run:
```
make clean
./autogen.sh
CXXFLAGS='-std=c++03' ./configure --without-miniupnpc
git apply leveldb.patch
make
```

**Comment by wirion** [comment]
It works, thanks Jonas!
