### ISSUE TITLE
Elements stuck, not syncing headers

### ISSUE THREAD

**Issue by inpharmaticist** [ElementsProject/elements#1060]
Elements-qt is connected to peers but doesn't seem to be receiving information
![image](https://user-images.githubusercontent.com/49789899/138419991-985a1eb0-7d1d-4248-92a2-83a76f8010ab.png)

Recently updated to v0.21 but this was an issue before updating (I think I had v0.18).
Running POP_os. Bitcoin-qt is running and synced prior to starting Elements.

Elements.conf file:
>mainchainrpcuser=user
mainchainrpcpassword=password
rpcuser=user
rpcpassword=password
fallbackfee=0.00000100

Bitcoin.conf file:
>rpcuser=user
rpcpassword=password
server=1
peerbloomfilters=1
disablewallet=0

**Comment by psgreco** [comment]
Is this still happening? what version are your peers running?

**Comment by inpharmaticist** [comment]
I deleted the blocks and chainstate folders. It works after resync.
