### ISSUE TITLE
e3def35d5c672aa87a32cbbdf6c2103bb039d0fb76a2f87a7f6062ba20ea1eee

### ISSUE THREAD

**Issue by Heareak** [ElementsProject/elements#1063]
#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by apoelstra** [comment]
Is this an accidental issue or a precommitment to something?
