### ISSUE TITLE
Pset output scalar decoding bug.

### ISSUE THREAD

**Issue by sanket1729** [ElementsProject/elements#1065]
The pset spec says that global scalars PSBT_ELEMENTS_GLOBAL_SCALAR must have value None, but as implemented they have value 0100 (a single vector containing the value zero)

In particular, https://github.com/ElementsProject/elements/blob/04cedf3f6be9e8eeb76af6206656ad2516d16f5a/src/psbt.h#L1425 should directly write 0 instead of SerializeToVector(s, std::vector<unsigned char>())

**Comment by jgriffiths** [comment]
Also, `UnserializeFromVector` should return immediately if `expected_size == 0`.
