### ISSUE TITLE
elements-0.21 vs master incompatibility

### ISSUE THREAD

**Issue by ajtowns** [ElementsProject/elements#1074]
I was trying out liquidtestnet and found I couldn't actually maintain a connection to anyone. I believe this is due to bitcoin/bitcoin#20564 having been backported to elements-0.21 in #1029 but not ported to master yet. Tweaking the code locally did indeed successfully work around the problem.

**Comment by apoelstra** [comment]
Thanks! Will be fixed then by the 22 rebase #1058 then I expect.

**Comment by psgreco** [comment]
#1058 was superseded by #1107 , which is already merged, and thus fixing this issue. Closing
