### ISSUE TITLE
Elementsd fails initial synchronization

### ISSUE THREAD

**Issue by Sosthene00** [ElementsProject/elements#1101]
**Expected behavior**

When started for the first time (empty datadir), elementsd should download and validates blocks up to the current chain tip.

**Actual behavior**

Elements is stuck at block 1463846 and won't download nor validate anything more despite having plenty of peers.

Besides it seems there's something wrong with block headers download too, since `getblockchaininfo` returns `header: 1724000`, which is not the current chain tip. So it seems that for some reason I won't download new block headers from peers either.

**To reproduce**

I simply started a new elements node on liquidv1, with `txindex=1`.

**System information**

Elements Core version elements-0.21.0.1, downloaded precompiled binary

Linux ~ 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

The logs are not showing anything of interest, it just stopped validating blocks at the said height, and then an endless flow of outbound connections and a few other lines but none that seems relevant to the issue.

**Comment by Sosthene00** [comment]
I'm trying a reindex now, and will start again from scratch if it's not enough.

**Comment by andreabonel** [comment]
What you're experiencing was solved in https://github.com/ElementsProject/elements/pull/1094 so please update to 0.21.0.2 and try again

**Comment by Sosthene00** [comment]
Thanks, I will update and close the issue if I can sync this time

**Comment by Sosthene00** [comment]
I'm synced, no pb, closing.
