### ISSUE TITLE
Failed to register asset

### ISSUE THREAD

**Issue by inpharmaticist** [ElementsProject/elements#1112]
Following the steps [here](https://docs.blockstream.com/liquid/developer-guide/proof-of-issuance.html) to register a liquid asset. After placing the liquid-asset-proof-<asset-id> in `well-known`, and running register_asset_<asset-id>.sh script I get
> failed verifying issuance commitment: invalid asset commitment

I expected the asset to register.

![image](https://user-images.githubusercontent.com/49789899/165669904-fe62c4e6-a450-41b9-b857-2701c237bca2.png)

Running Elements-0.21.0.2
Pop!_OS

Content of asset proof
> Authorize linking the domain name inpharmaticist.keybase.pub/ to the Liquid asset 967a530505be5ceeb0fbc996af32b4655fb4be8b96b2a2b0eff81f2828388713

Content of register_asset script
> curl https://assets.blockstream.info/ --data-raw '{"asset_id":"967a530505be5ceeb0fbc996af32b4655fb4be8b96b2a2b0eff81f2828388713","contract":{"entity":{"domain":"inpharmaticist.keybase.pub"},"issuer_pubkey":"02617291a422b548ed05d9e42937e060483da3aa61e8b9c0f3e968a68279556dd9","name":"Larry Coin","precision":1,"ticker":"LRYCN","version":0}}'

**Comment by philippem** [comment]
We checked that the domain proof file has been deployed.

Is it possible that the contents of the `register_asset` script posted above is different than the `CONTRACT_HASH` string that generated and hashed before the RPC call to `issue_asset` ? if the contract hash in the issuance transaction https://blockstream.info/liquid/tx/4875d65624d91813b8de2acfac611d56e27523c8e00cda3974ee308f4f8b8dc6?input:0&expand is different that the sha256 of the string passed in the curl POST, the error "failed verifying issuance commitment: invalid asset commitment" will result.

**Comment by inpharmaticist** [comment]
Thanks. By

> sha256 of the string passed in the curl POST

do you mean a sha 256 checksum ofthis part?

> '{"asset_id":"967a530505be5ceeb0fbc996af32b4655fb4be8b96b2a2b0eff81f2828388713","contract":{"entity":{"domain":"inpharmaticist.keybase.pub"},"issuer_pubkey":"02617291a422b548ed05d9e42937e060483da3aa61e8b9c0f3e968a68279556dd9","name":"Larry Coin","precision":1,"ticker":"LRYCN","version":0}}'

That yields 4981cd8d36955a43e5d9481fe273d1be8923de6016d4569cd6a5f7b84d554da5.  To answer your question, in `issue_and_prepare_register.sh` I actually had `DOMAIN="inpharmaticist.keybase.pub/"`.  I removed the forward slash at the end of the URL in 'register_asset_....sh' because I got the following rejection.

>invalid `entity` domain name: must only contain allowed characters

Could having the forward slash in the `issue_and_prepare_register.sh` have screwed it all up?

**Comment by andreabonel** [comment]
> Could having the forward slash in the `issue_and_prepare_register.sh` have screwed it all up?

Likely...
I verified that your file https://inpharmaticist.keybase.pub/.well-known/liquid-asset-proof-967a530505be5ceeb0fbc996af32b4655fb4be8b96b2a2b0eff81f2828388713 still has the / in the domain.
I'll keep testing either way.

**Comment by andreabonel** [comment]
I did the following:

1) ran `issue_and_prepare_register.sh` with the **/**
2) placed the `liquid-asset-proof-` file in a folder named `.well-known` in the root of my domain
3) ran `register_asset_<asset-id>.sh` and showed this error: 
```
invalid entity domain name: must only contain allowed characters
```
4) deleted the **/** from the `liquid-asset-proof-` file
5) ran `register_asset_<asset-id>.sh` and showed this error: 
```
failed verifying issuance commitment: invalid asset commitment
```

I guess the script has a bug, we will address that.
I suggest that you should maybe re-issue the asset.
Thanks!

**Comment by inpharmaticist** [comment]
Gotcha, so re-issue without the `/`? Thanks for your help!

**Comment by inpharmaticist** [comment]
It worked!
