### ISSUE TITLE
Elements-qt title correction of network name (v21.99.0)

### ISSUE THREAD

**Issue by andreabonel** [ElementsProject/elements#1123]
There's a bug in elements-qt title, in v21.99.0:
![Screenshot elements-qt with both different network names](https://user-images.githubusercontent.com/94554885/179571859-6fc84bf0-4fbf-45ff-bab5-7a663f325e76.png)

It was ok in v0.21.0.2 :
![Screenshot elements-qt 0 21 0 2](https://user-images.githubusercontent.com/94554885/179571954-7a30e30d-aacb-499a-a8a4-46eb7600b6e9.png)

**Comment by psgreco** [comment]
Fixed by https://github.com/ElementsProject/elements/pull/1130
