### ISSUE TITLE
Document Assets API

### ISSUE THREAD

**Issue by martindale** [ElementsProject/elements#113]
Let's begin the process of documenting the full API for asset issuance.

[edits by @bteitelb]
Assets API needs to be accessible to newbies, for use in trainings, and for use by integration partners.

@jtimon could you start this? Please use @ChristopherA for QA (i.e. Does it make sense to him?), as well as copyediting and technical writing support.

**Comment by bteitelb** [comment]
@wtogami, I know you've been concerned that we haven't been making progress on this issue. Please describe specifically what you'd like to see come out of it.

**Comment by ChristopherA** [comment]
@harding has a solid, near final draft, of the Elements Assets API in his gist. The gist has some small final questions and needs final technical review by @wtogami before calling this issue closed, but we are very close.
