### ISSUE TITLE
Elements-qt fails to show the amount in the sender's wallet after using the Send button

### ISSUE THREAD

**Issue by andreabonel** [ElementsProject/elements#1151]
The problem is: when you use the "Send" button in the gui, the amount in the sender's wallet isn't correctly shown.

Notes:
- Even when the amount in the sender's wallet isn't shown correctly, the transaction is successfully done.
- The problem occurs when sending coins to another wallet (even in the same node); strangely when sending coins to the same wallet it works ok.
- The bug affects when using the "Send" button in the gui; it doesn't affect the rpc.

Tested on Linux (0.21.0.2 and 22.0 rc4) and macos (22.0 rc4).

In this case I've just sent 0.0004 L-BTC but it shows 0.00000001
![Screenshot from 2022-08-25 16-40-00](https://user-images.githubusercontent.com/94554885/186774587-ba5145bd-c973-407e-8546-e77818e415f6.png)

Also in the details the debited amount is incorrectly shown (even when the net amount is the right one):
![Screenshot from 2022-08-25 16-44-32](https://user-images.githubusercontent.com/94554885/186788819-18cd04bf-507c-4e3c-9e03-04185d22778f.png)

Console shows the same incorrect value:
![Screenshot from 2022-08-25 17-16-55](https://user-images.githubusercontent.com/94554885/186786279-5183165d-6958-43fe-9e23-562ce741ce40.png)

The same transaction from the other side, Wallet2 (receiver) is appropriately shown:
![Screenshot from 2022-08-25 17-18-09](https://user-images.githubusercontent.com/94554885/186786412-332f581a-aa74-4f36-b78c-749a4a02e2c9.png)

I've tried restarting the wallet and restarting elements-qt, but the problem persists.
Maybe an important detail: I've tried with the unconfidential address, and the amount is adequately shown.

**Comment by delta1** [comment]
> I've tried with the unconfidential address, and the amount is adequately shown. 

@andreabonel so the bug you're seeing here is only when sending to confidential address?
