### ISSUE TITLE
add unblinded value and asset input fields to PSET 

### ISSUE THREAD

**Issue by philippem** [ElementsProject/elements#1153]
Apps running on highly constrained hardware wallets wish to display unblinded value and asset inputs to the user, when confirming transactions specified by a PSET. These same devices are unable to perform unblinding due to hardware and software constraints.

It has been requested that unblinded value and asset input fields be added to the PSET spec, so that the companion app (which runs on the host) may provide this information to the device, along with the proofs and commitments. The device would perform verification independently, before displaying the unblinded values.

**Proposed Solution**

New elements per-input fields for unblinded value and asset, e.g.

```
PSBT_ELEMENTS_IN_VALUE
PSBT_ELEMENTS_IN_ASSET
```

**Comment by apoelstra** [comment]
We also need proof fields for these assets, and we need the equivalent fields for asset issuances.

**Comment by apoelstra** [comment]
Actually, I believe we have those. But what we **do** need is a field to signal to the wallet whether or not issuances should be blinded. (And Elements would need to respect this.)

**Comment by apoelstra** [comment]
To clarify, we need proof fields for the assets. What we *don't* need are the issuance-related things, which we already have.
