### ISSUE TITLE
walletcreatefundedpsbt needs to (optionally) add explicit value fields 

### ISSUE THREAD

**Issue by philippem** [ElementsProject/elements#1179]
In a recent change to the PSET spec, new input keys were added to support the communication of unblinded values, for the  benefit of resource-constrained environments.  See the requesting issue https://github.com/ElementsProject/elements/issues/1153

The new input keys are

```
PSBT_ELEMENTS_IN_EXPLICIT_VALUE
PSBT_ELEMENTS_IN_VALUE_PROOF
PSBT_ELEMENTS_IN_EXPLICIT_ASSET
PSBT_ELEMENTS_IN_ASSET_PROOF
PSBT_ELEMENTS_IN_BLINDED_ISSUANCE
```

Support for these keys was added in the PRs

https://github.com/ElementsProject/elements/pull/1157
https://github.com/ElementsProject/elements/pull/1165

The current `walletcreatefundedpsbt` RPC does not set these fields in its response, nor provides a way for the caller of the RPC to request that they be populated (possibly by using the 4th optional `options` argument).

**To reproduce**

See the test vector generator provided at
 https://github.com/miketlk/testvectors/blob/ca7a6a2f00a61d881168a2ae498fee05e130c1fe/tests/test_pset.py#L123-L146

**System information**

`elementsd` commit e0c911a57 on `elements-22.x` branch

**Comment by apoelstra** [comment]
cc @achow101 can you add an option to `walletcreatefundedpsbt` to populate these fields?
