### ISSUE TITLE
Include signed source bundle checksums 

### ISSUE THREAD

**Issue by MrHash** [ElementsProject/elements#1196]
Can you include the [source bundle](https://github.com/ElementsProject/elements/archive/refs/tags/elements-22.0.2.tar.gz) checksums to the `SHA256SUMS.asc` file, otherwise is it possible to verify the source bundle checksum some other way?

**Comment by psgreco** [comment]
that file is automatically generated by github so I'm not comfortable signing it, I've uploaded the tarball generated by the guix build and a new SHA256SUM file with all the previous signatures plus the source tarball.
Please confirm that it's ok so we can close this

**Comment by MrHash** [comment]
Ok that's great, going forward will you roll the tarball source checksum into the usual `SHA256SUMS.asc` file?

**Comment by psgreco** [comment]
Yes, I just uploaded an extra file now because changing the current seems like a big red flag
