### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by me639276639936** [ElementsProject/elements#1240]
**Describe the issue:**
Sync fails with "out of memory" error, even though task manager on RPI shows sync was only using half of available RAM.

**What behavior did you expect?** To sync the Liquid Chain successfully.

**To reproduce issue:** Run elementsd

**What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?** Bitcoin Core v22.0.0, from Bitcoin Core website

**What type of machine are you observing the error on (OS/CPU and disk type)?** RPI4, 8GB Ram, 128 GB SD

**GUI-related issue? What is your operating system and its version? If Linux, what is your desktop environment and graphical shell?** Raspian

**Any extra information that might be useful in the debugging process:**

**bitcoin.conf settings**
server=1
daemon=1
rpcuser=....my user
rpcpassword=...my password
datadir=/home/usr/.bitcoin
prune=1000
dbcache=100
maxmempool=200
maxconnections=30
par=1

**elements.conf settings**
mainchainrpcuser=....my user
mainchainrpcpassword=...my password
mainchaindatadir=/home/usr/.bitcoin
prune=1000
dbcache=100
maxmempool=200
maxconnections=30
par=1
chain=liquidv1

**Comment by psgreco** [comment]
which version of elements are you using?
in low memory environments, it's recommended to use the experimental setting `trim_headers=1`.

**Comment by me639276639936** [comment]
22.1.1

Thanks for the tip. Will try

**Comment by psgreco** [comment]
Thanks for letting us know, closing..,
