### ISSUE TITLE
Integrate pegging.py in qa/rpc-tests/feature_fedpeg.py

### ISSUE THREAD

**Issue by jtimon** [ElementsProject/elements#127]
Currently pegging.py is run indepdently instead of using rpc-tets.py like the rest.

Currently:
```
python3 ./qa/rpc-tests/pegging.py /home/myhost/bitcoin-0.15.1/bin/
```

We should move to something like:
```
python3 ./qa/pull-tester/rpc-tests.py feature_fedpeg --parent-binary=/home/myhost/bitcoin-0.15.1/bin/
```

while still maintaining the existing test passing by using its same binary for the parent chain:
```
python3 ./qa/pull-tester/rpc-tests.py feature_fedpeg 
```

**Comment by stevenroose** [comment]
I think #415 closes this issue, no?

**Comment by instagibbs** [comment]
yep

**Comment by jtimon** [comment]
Yeah, I think what really really fixes it is https://github.com/ElementsProject/elements/pull/418 but is merged too now.
