### ISSUE TITLE
Bad enumeration of script errors

### ISSUE THREAD

**Issue by roconnor-blockstream** [ElementsProject/elements#1285]
https://github.com/ElementsProject/elements/blob/20c5630f8c13c3df37c8a34c96fdbeceb8af1e27/src/script/script_error.h#L87

has incorrectly inserted new Elements errors into this enumeration.  All the new elements errors need to go **before** `SCRIPT_ERR_ERROR_COUNT`, which isn't actually a real error.  Then `SCRIPT_ERR_LAST` needs to be reset to `SCRIPT_ERR_ERROR_COUNT`, as it originally was.

AFAICT the only consequences of this error are for the fuzzer.

I'm not sure that having both `SCRIPT_ERR_LAST` and `SCRIPT_ERR_ERROR_COUNT` makes sense, but that is how it is in Bitcoin at the moment.

cc @uncomputable

**Comment by uncomputable** [comment]
The error exists on master: https://github.com/ElementsProject/elements/blob/master/src/script/script_error.h#L85

**Comment by uncomputable** [comment]
[This fuzz test](https://github.com/ElementsProject/elements/blob/20c5630f8c13c3df37c8a34c96fdbeceb8af1e27/src/test/fuzz/script.cpp#L136) is the only place where `SCRIPT_ERR_ERROR_COUNT` is used. `SCRIPT_ERR_LAST` is not used at all.

I think it is safest to keep both errors in case Bitcoin Core starts using either in the future.
