### ISSUE TITLE
liquidregtest is missing from --help output

### ISSUE THREAD

**Issue by grubles** [ElementsProject/elements#1290]
`elementsd --help`

```
  -chain=<chain>                                                                           
       Use the chain <chain> (default: liquidv1). Reserved values: main, test,             
       signet, regtest, liquidv1, liquidv1test
```

This makes it hard to discover for emulating Liquid locally for testing purposes. `liquidregtest` seems fairly undocumented in general. Is it the same as `elementsregtest` or are there differences? `elementsregtest` is also missing from the help too.

**Comment by psgreco** [comment]
`liquidtestnet` is a reserved value and should be added. Anything else, like `liquidregtest` or `elementsregtest` are fallback values and they all have the same specs
