### ISSUE TITLE
Increase block size

### ISSUE THREAD

**Issue by afeezaziz** [ElementsProject/elements#1304]
I am planning to have a sidechain thats focused on computation and a lot of data to be put on blockchain. Is there a way to increase block size from 4MB to perhaps 200MB?

**Comment by psgreco** [comment]
You should change the value in consensus.h and build your own version.
https://github.com/ElementsProject/elements/blob/master/src/consensus/consensus.h#L13
```
static const unsigned int MAX_BLOCK_SERIALIZED_SIZE = 4000000;
```

**Comment by afeezaziz** [comment]
I think this also can be changed in the .conf right?

**Comment by delta1** [comment]
> I think this also can be changed in the .conf right?

no it is only set in the source code, so would have to be changed there and recompiled from source. 

docs on how to build are in the `doc` folder 

https://github.com/ElementsProject/elements/blob/master/doc/build-unix.md

**Comment by afeezaziz** [comment]
Ok, thank you.
