### ISSUE TITLE
Can sendmany be used to send assets?

### ISSUE THREAD

**Issue by maximusmaximalistus** [ElementsProject/elements#1305]
I was checking the documentation and wondering if  `sendmany` could be used to send assets too. 

https://elementsproject.org/en/doc/23.2.1/rpc/wallet/sendmany/

But there is no reference to the asset in the documentation of the `sendmany` command.

**Comment by delta1** [comment]
so as an example to send 2 different assets: 

```
sendmany "" {"addr1":1.0, "addr2":2.0} 0 "comment" [] true 1 "unset" {"addr1":"asset1", "addr2":"asset2"}
```
