### ISSUE TITLE
Green wallet seed import can't compatible with sideswap wallet

### ISSUE THREAD

**Issue by yshwanth** [ElementsProject/elements#1306]
Description :  Green uses native segwit default, so when user tried to import seed onto sideswap which is nested segwit not able to see funds.
- peg-ins, peg outs valid on legacy nested segwit, so maybe moving towards a standard descriptor based ease use of wallet setup for new users onboarding to Liquid .

**Comment by yshwanth** [comment]
This is applicable to Aqua wallet too

**Comment by delta1** [comment]
Hi @yshwanth thanks for reporting but this is unrelated to Elements, please open your issue in one of the Green repos 

- [desktop](/Blockstream/green_qt)
- [ios](/Blockstream/green_ios)
- [android](/Blockstream/green_android)

**Comment by yshwanth** [comment]
Thanks update in one of above repos.
