### ISSUE TITLE
How to use with bitcoinlib-js

### ISSUE THREAD

**Issue by afeezaziz** [ElementsProject/elements#1308]
Hello,

I would like to test elements/liquid with a Javascript library, how can I set up the rpc node and node host address to be used with elements?

Thanks.

**Comment by delta1** [comment]
Hi there you can see the nodejs example of using Elements RPC here: 

https://elementsproject.org/elements-code-tutorial/other-languages#nodejs

**Comment by delta1** [comment]
https://github.com/vulpemventures/liquidjs-lib

**Comment by afeezaziz** [comment]
> https://github.com/vulpemventures/liquidjs-lib

How do I generate an address based on custom element standalone chain?

**Comment by jgriffiths** [comment]
@afeezaziz wally wrappers are available through npm, please see https://github.com/ElementsProject/libwally-core/tree/master/src/wasm_package

The tests give examples of usage, e.g. in https://github.com/ElementsProject/libwally-core/tree/master/src/wasm_package/test/confidential_address.js you can replace `wally.WALLY_CA_PREFIX_LIQUID` with your own address prefixes.

**Comment by afeezaziz** [comment]
How do I get the address prefix from a standard element blockchain. No customisation, I'm exploring how to get cheap UTXO.

**Comment by jgriffiths** [comment]
The address prefixes (there are more than one) are part of the chain parameters which uniquely identify the chain. You are generally expected to have this info hard-coded into your client app for the chain(s) you expect to interact with.

You can see the default address prefixes and other unique chain info for Elements in `src/chainparams.cpp`, look for `base58Prefixes` and `bech32_hrp`/`blech32_hrp`.

Note that this repo is not the place for general elements support, please follow the support links on blockstream.com to find more suitable venues such as developer telegram channels etc.

**Comment by afeezaziz** [comment]
Hello, I would love to get some general elements support but I am unable to find the " developer telegram channels etc."

Anyway, thank for you for this. I need to find out how can I get the configurations based on the elements chain started.
![Uploading Screenshot 2024-01-11 at 12.17.49 PM.png…]()
