### ISSUE TITLE
Message signing only works with legacy addresses

### ISSUE THREAD

**Issue by Czino** [ElementsProject/elements#1309]
**Expected behavior**

When using `elements-cli signmessage`, I would expect that I can sign with any address that belong to my wallet and if message signing is not supported for the address type, provide a clearer error message.

**Actual behavior**

Instead, for all address types byt `legacy` an error code is thrown.

**To reproduce**

```
elements-cli signmessage $(elements-cli getnewaddress "") "Message"
error code: -3
error message:
Address does not refer to key

elements-cli signmessage $(elements-cli getnewaddress "" "legacy") "Message"
IBkL209BPZxg26/BoAGz9zLtFG7GDATP9dJtDoeLMqxyKaoLfZMgYR+pdrX3ZHslqIQBZTjO/afuxpeapcOup4U=

elements-cli signmessage $(elements-cli getnewaddress "" "p2sh-segwit") "Message"
error code: -3
error message:
Address does not refer to key

elements-cli signmessage $(elements-cli getnewaddress "" "bech32") "Message"
error code: -3
error message:
Address does not refer to key
```

**System information**
Elements Core:23.2.1

**Comment by Czino** [comment]
Additionally, because [BIP137](https://github.com/bitcoin/bips/blob/master/bip-0137.mediawiki) style message signing only works for a small set of address types, can [BIP322](https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki) be supported?

**Comment by delta1** [comment]
also a very interesting comment from gmax here: https://github.com/bitcoin/bitcoin/issues/10542#issuecomment-306625829

**Comment by Czino** [comment]
Hi @delta1, I think [BIP322](https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki) would be the way forward for new kinds of addresses.
If you think that support needs to be implemented in bitcoin-core first, then this issue can be closed. A [PR already exists](https://github.com/bitcoin/bitcoin/pull/24058) but has been closed.

**Comment by delta1** [comment]
I think BIP322 will only be supported if it's inherited from upstream. Closing for now, feel free to re-open.
