### ISSUE TITLE
Block proof invalid after block 431

### ISSUE THREAD

**Issue by afeezaziz** [ElementsProject/elements#1311]
I am following https://elementsproject.org/elements-code-tutorial/block-creation but every single time, im changing the signing the blocks from every second to every minute to every 10 minutes, but every single time, it would refuse to sign at block 431.

**Comment by afeezaziz** [comment]
I notice that an [issue](https://github.com/ElementsProject/elements/issues/767) also refers to same thing.

**Comment by delta1** [comment]
https://github.com/ElementsProject/elements/issues/767#issuecomment-550113108

**Comment by afeezaziz** [comment]
> try adding the conf or arg `con_dyn_deploy_start=2021097111`

Error: Error parsing command line arguments: Invalid parameter -con_dyn_deploy_start=2021097111

This is the error from the command line.

**Comment by delta1** [comment]
sorry, it's dyna 

`con_dyna_deploy_start`

**Comment by afeezaziz** [comment]
> sorry, it's dyna
> 
> `con_dyna_deploy_start`

same error as the parameter before:

`Error: Error parsing command line arguments: Invalid parameter -con_dyna_deploy_start`

**Comment by delta1** [comment]
sorry it was changed to evbparams

`-evbparams=dynafed:0:::`  to disabled dynafed, which is listed in the assets tutorial 

https://github.com/ElementsProject/elements/blob/2d298f7e3f76bc6c19d9550af4fd1ef48cf0b2a6/contrib/assets_tutorial/assets_tutorial.py#L484

**Comment by afeezaziz** [comment]
I was having that problem, when following the tutorial exactly...

`-signblockscript=abcd123 -con_max_block_sig_size=214 -evbparams=dynafed:0:::`

It wont go above block 413, unless i changed the max block from 214 then to something else then back to 214. Is that acceptable hot fix solution?

**Comment by afeezaziz** [comment]
> sorry it was changed to evbparams
> 
> `-evbparams=dynafed:0:::` to disabled dynafed, which is listed in the assets tutorial
> 
> https://github.com/ElementsProject/elements/blob/2d298f7e3f76bc6c19d9550af4fd1ef48cf0b2a6/contrib/assets_tutorial/assets_tutorial.py#L484

Playing around with -evbparams will reach same conclusion, where block signing stops at 431.

**Comment by afeezaziz** [comment]
Tried doing this with changing a few other flags, result is the same except when i change `-con_max_block_sig_size=214` from 214 to something higher like 210004.

**Comment by afeezaziz** [comment]
@delta1 do you know how I can do this?

**Comment by afeezaziz** [comment]
I am still stuck with this issue... I am unable to run elements blockchain, when using the federation signing blocks method.

**Comment by afeezaziz** [comment]
It has been more than a month, I have tried so many ways to make sure chain can pass after the block....

**Comment by delta1** [comment]
You will have to post more information about what exactly you're doing. Like a full representative sample that can be used to reproduce your issue.

**Comment by delta1** [comment]
github issues is for code bugs/features and not for tech support 

please create a post on the liquid community site that clearly describes what you are trying to do, and with steps to reproduce your issue so that we can assist you there 

https://community.liquid.net/c/developers/

**Comment by afeezaziz** [comment]
Following the exact tutorial provided by Blockstream, and found out that the code does not function as expected is not a bug but a tech support issue? Ok, I will write again in the "tech support" forum.
