### ISSUE TITLE
Can´t mint tokens

### ISSUE THREAD

**Issue by TaniaLea** [ElementsProject/elements#1315]
Dear Elements,

I followed all the manual steps for emitting a token but kept getting errors. The cause of these errors seems to be that the syncing hasn't finished but as you can see in the picture linked below it says I have to wait 5 years. Moreover, I downloaded the Elements software on a new computer (also Windows) and kept facing the same issue.
I had already sent $30 worth of Liquid to the wallet in Elements to mint the token but the balance won't update due to the pending syncing update. Please let me know how to proceed as I wish to mint the tokens.

Sincerely,

https://p25.zdusercontent.com/attachment/9866144/kAcij8KJusYcien3gow2S9za7?token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2In0..8PLkwXY2Odm0aOPJab_rcQ.nmeFRpUAYe25xPEyIrdRh2VJPLte9FcOv0qCOBy3Qg-vlqhWyDxgQp6-pPKQIsLNqz6m5f_Dy6_-Emg47KCjTpQbbQE7VHIFglyJNYzOYi829VIsi_GR-9o5I_VRIpdtp9JfnVAQTlhd5rP_veL1E4ZG0o-FUR14755ctuddP2Xg29XyozxZcJxH3JhGi2k8CExMWXHU1uRGP2HlcpSdkY4uHmPOBb-DLFWFpyJPlmU15wftl-BSWz2327EW4WhWYFySEGyG-zZag0_1R_EOyZT3f_XxRPyuUhKtY81nYfE.kMdKzxoGgjBMKJoE9gfErQ

**Comment by delta1** [comment]
hi there unfortunately you will have to wait until your node is synced up. it shouldn’t take 5 years though, that is just the date on the earliest blocks. the chain is about 20GB that has to be downloaded and verified, so just leave it running day and night.
