### ISSUE TITLE
Wallet migration fails with confidential transactions

### ISSUE THREAD

**Issue by bitchad42** [ElementsProject/elements#1320]
**Expected behavior**

Exporting a wallet and importing it again on a different node should bring all the data, including confidential transactions, whose details should be visible through the argument `gettransaction`.  

**Actual behavior**

Instead it brings all transactions, they appear counted on the field `txcount`, but even after rescan the balance remains zero or differs, due to the fact that confidential transactions remain opaque to the node.

**To reproduce**

Get a node with only confidential transactions, export the wallet through the argument `dumpwallet` and import it on a fresh install of the node on a different machine through the argument `importwallet`, rescan and compare balances.

**System information**

Origin and destination nodes respectively:
Elements Core RPC client version v23.99.0-2d298f7e3f76-dirty
Elements Core RPC client version v23.2.1

**Comment by bitchad42** [comment]
This issue added to the fact that there is no support for wallet seeds (passphrase) means that the security of the funds relies on the integrity of a single .dat file. Even doing backups regularly, if it were to become corrupt, all the transactions that went to new addresses would be lost forever.

Please provide with a documented method where we can export and import a wallet including confidential transactions reliably.

**Comment by delta1** [comment]
Hey thanks for reporting, I think you would need to [dumpmasterblindingkey](https://elementsproject.org/en/doc/23.2.1/rpc/wallet/dumpmasterblindingkey/) from the node you're exporting from, and [importmasterblindingkey](https://elementsproject.org/en/doc/23.2.1/rpc/wallet/importmasterblindingkey/) on the new node

**Comment by bitchad42** [comment]
This seems to be working well, however the documentation says:
> Recommended use is **only** for wallet recovery using this in conjunction with `sethdseed`.

**Comment by delta1** [comment]
I think the HD seed is part of your wallet.dat (so it’s deriving the right addresses) you just needed the master blinding key as well

**Comment by bitchad42** [comment]
Correct I just found it among the other addresses.
Also noticed that `dumpmasterblindingkey` is not necessary since the master blinding key already comes in the wallet dump.
I think this procedure (`importwallet` + `importmasterblindingkey` from the comments in the wallet dump file) should be documented somewhere.
However more than a bug this is a documentation problem, not a software one, so I'm closing this issue.

**Comment by bitchad42** [comment]
No luck. Tried this procedure and keys are still missing.

This is the procedure I am doing now:

### Export wallet
On the old node:
```bash
elements-cli dumpwallet "mywallet_backup.txt"
```

### Import wallet
On the new node:
```bash
elements-cli createwallet "mywallet" false true $wallet_encryption_passphrase true false true
elements-cli importmasterblindingkey $master_blinding_key
elements-cli sethdseed false $hd_seed
elements-cli rescanblockchain
```

This results in missing addresses.
As far as I understand new addresses were generated on the old node that do not exist on the new one.
Is there any way in which we can reliably derive a wallet without missing transactions/balance?

**Comment by bitchad42** [comment]
Never mind, this is a problem inherited from bitcoin-core. I guess it won't fix.

**Comment by delta1** [comment]
> Never mind, this is a problem inherited from bitcoin-core. I guess it won't fix.

sorry to hear that. do you have a reference to the issue in bitcoin core?
