### ISSUE TITLE
Support for Jade hardware wallet

### ISSUE THREAD

**Issue by nakoshi-satamoto** [ElementsProject/elements#1323]
It would be very beneficial to have hardware support with Jade which is a (the only?) Liquid hardware wallet.

Privacy Benefits:
Right now the lightweight Liquid wallet Green does not actually support connecting to one's own node which is harmful for privacy because electrum servers leak all your associated addresses, and it seems that most if not all users are not actually able to run their own liquid electrum node. More details are here https://github.com/Blockstream/green_qt/issues/117 and https://github.com/Blockstream/esplora/issues/489  By having hardware wallet support in elements it would let users use Jade with their own local liquid node.

Hardware Wallets are needed for Liquid:
I have not been able to get Jade to work with Green wallet. Details are here https://github.com/Blockstream/green_qt/issues/118 It would be very beneficial to have the ability to use Liquid with a hardware wallet for security purposes so that keys containing funds are not kept on a hot wallet.

Even if the blind oracle virtual secure element function is not supported at first in Elements, I think it would be good to at least support USB connection or signing of transactions or QR code method. If QR codes are not supported directly in Elements then it could be done with something like qrencode and zbarcam (external software) and users could import a "watch only wallet", and using elements to manage transactions, then signing transactions on the Jade. 

If this is already possible to use Jade with Elements for Liquid, then documenting this would be good.

**Comment by delta1** [comment]
hey @nakoshi-satamoto 

Yes it would be beneficial. Elements is a fork of Bitcoin Core, so it uses the same library [HWI](https://github.com/bitcoin-core/HWI), which is where additional support for using Jade with Liquid will be required. 

It should be possible to use Jade with Liquid and Green. I did confirm your error on desktop so will ask the Green team to look into it. It does appear to work on mobile Green if that's something you want to try, I just tested on iOS. 

 If you want to try out [Liquid Wallet Kit](/blockstream/lwk) it's a new CLI application which supports Jade, and you can set it to use your own electrs instance, and I believe it should support Elements too in the near future.

**Comment by delta1** [comment]
> I did confirm your error on Green desktop 

@nakoshi-satamoto this is a known issue in jade firmware 1.0.28. it is fixed in 1.0.29 which will be released shortly, or you can downgrade your jade firmware to 1.0.27 - both of which I have confirmed are working to create Liquid accounts.

**Comment by nakoshi-satamoto** [comment]
Yes like delta1 said, the compatibility between jade and Green is resolved now )
