### ISSUE TITLE
elements-qt 23.2.2rc1 and master crash at shutdown on M1 macOS

### ISSUE THREAD

**Issue by grubles** [ElementsProject/elements#1347]
On M1 macOS arm64, elements-qt 23.2.2rc1 and master @ e1d6b66 will crash after the wallet has been decrypted and the application is shut down.

 I've attached the macOS crash report along with Fedora 40 x86_64 valgrind logs during elements-qt shutdown. 

[fedora_valgrind_log.txt](https://github.com/user-attachments/files/16365429/fedora_valgrind_log.txt)
[macos_shutdown_crash.txt](https://github.com/user-attachments/files/16365430/macos_shutdown_crash.txt)

**Comment by psgreco** [comment]
Discussed with @grubles and it doesn't seem to be reproducible anymore, closing
