### ISSUE TITLE
[0.13.1] fundrawtransaction is moderately broken, results in blinded outputs

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#137]
During transaction funding, for fee estimation purposes, we have the transaction temporarily blinded, but then these should be discarded, allowing the caller to call `blindrawtransaction`. Currently the change output and OP_RETURN dummy outputs are kept.

**Comment by jonasnick** [comment]
Currently the effect is that the following script
```
#!/bin/bash

CLI="beta-cli -regtest"

#use fresh regtest network
$CLI generate 100 > /dev/null

tx=`$CLI createrawtransaction '[]' '{"mg1dsj2MKpHq7KQRmaeCLQsE33dQYjK7TJ": 0.001}'`
tx=`$CLI fundrawtransaction $tx | jq -r '.hex'`
$CLI decoderawtransaction $tx
txid=`$CLI sendrawtransaction $tx`
echo $txid
```
fails with 
```
error code: -26
error message:
16: bad-txns-fee-outofrange
```
which is a misleading error given that you actually have to do `blindrawtransaction`.

**Comment by instagibbs** [comment]
Ok `fundraw` is going to need a pretty big overhaul.

In your case `fundraw` appends a blinded change output, as well as a blinded 0-value OP_RETURN output, since it can't blind it correctly otherwise. Currently we were only checking for the very last output added to the CWalletTx to be a fee, and appending it to the returned transaction. This is clearly not the case when an OP_RETURN is added as well, so it fails to add both outputs.

In addition, if there are multiple added change outputs, only a single one is being added at this time, since `nChangePosInOut` only handles a single one.

Lastly, this call assumes that nothing about the outputs have changed, except for a single change output. This isn't the case for us since we have fee outputs, and sometimes additional op_return outputs to blind the change output correctly.

Proposal for now:
1) Do the blinding dry-run, like it is now
2) After the call, wipe CMutableTransaction's outputs, and re-add the outputs directly from CWalletTx
3) Do the same with output witnesses
4) Adapt `changepos` result and `changePosition` argument to handle multiple assets correctly

This I think will give us a fully functioning call.

Remaining issues I'm looking for more feedback on:
1) We need to make sure that we aren't massively over-paying in fees. The previously-filled transaction may have fee outputs, and these will need to be collected together or accounted for in some way. In our naive way we essentially pretend they don't exist, and fund the transaction in full. I think merely accounting for them is best, so that we don't have to mess with output ordering at all.
2) Have an option that allows for fee "canonicalization". Group fees together by asset type and put them at the end of the output vector. This likely conflicts with any attempt at picking change indices.
3) Remove the blinding of the change output, and remove the possible OP_RETURN output. This requires using the wallet functionality to unblind that particular output.

My proposal:
1) Do the blinding dry-run, like it is now
2) After the call, wipe CMutableTransaction's outputs, and re-add the outputs directly from CWalletTx
2b) Remove the blindings/witness data for any new blinded outputs (future work?)
3) Do the same with output witnesses (I think we can remove this step if 2b is implemented)
3) Gather fee outputs by type and stick them on the end of the output vector. There's no reason outputs shouldn't be gathered at the end since they're uniquely marked as such already.
4) Adapt `changepos` result and `changePosition` argument to handle multiple assets(?)
5) `fundraw` should be more generally adapted to multiasset setting
