### ISSUE TITLE
Min- and max-range in CT should be the same always

### ISSUE THREAD

**Issue by kallewoof** [ElementsProject/elements#171]
Right now it is possible to deduce information about a transaction's value by simply taking `max - ((max-min) * K)` where `K=0.1` or similar. This may not always be the case but has been so in my experiments so far. The original idea I believe was that the min and max values should always be the same, i.e. no matter if I send 1.0 or 10000.0, the max should be e.g. 2000000 or something similar probably-max:ish.

**Comment by instagibbs** [comment]
We've discussed increasing the default number of bits to hide by default by ~4 or so, which covers up to 687 BTC with a 11% performance hit.

Wallet users can always do this on their own by setting `-ct_bits` to some number higher than the default 32.

**Comment by kallewoof** [comment]
Adam Back mentioned that it may be possible to use exponent/mantissa to decrease the requirement and avoid having to increase the bit count:

> set base10 exponent = 8, and then 1btc = 1yen in rpc, but the range goes from 0-2^32 yen (with unused 8-bits of precision below) or probably eg more usefully? base10 exponent=6, then 1btc = 1 yen and you have two digit decimal precision on yen if there are very low value fees or such.

Ideally though I guess we want to user-define the precision on a per asset basis so we can say that 100 "kalle-satoshis" is 1 "kallecoin".

**Comment by jonasnick** [comment]
To clarify, as long as your using less than 2**32 "satoshis", the max is `42.94` "btc". Otherwise max is the smallest power of 2 satoshis such that the value is covered. You might be experimenting with issued assets and therefore dealing with values that are larger than 4294967296 currency units. In such cases your `K` should be in `[0, 0.5]`. That's definitely undesirable. However, in most cases you don't need that much precision. If you treat the smallest currency unit (satoshi in the case of Bitcoin) as 1 USD cent, you'd be able to send up to 43 million USD (or with the switch to 36 bit rangeproofs 687 USD) without increasing max.

At the moment this is inconvenient to work with because 1 USD cent would be represented as 0.00000001 in the RPC. But this seems to be just a presentation issue and doesn't require using the CT exponent.

**Comment by kallewoof** [comment]
@jonasnick We were dealing with values in the range 10 to 500-600 or so, and the min/max was different each time. I'll see if I can reproduce this on latest master.

**Comment by kallewoof** [comment]
A transaction sending 1000 of an asset, with a change of 9000 and a 200k pass-through for blinding reasons. Each of these can be approximated by simply reducing a proportion of the max-value from the max-value. See below

```{
  "txid": "ae48ad86e907cba85d1d8e75379c0c1e26d7235dbf44d622137cc26b05224045",
  "hash": "026d6886eaeadf3006b1d1cc43a6de59bf747eb7ec2dcc1c0e2fc4462156b022",
  "withash": "29c8a80775bc3a07ea4c5baae5ce841ba49d0fd93bef0ccd93043dfed0b60af1",
  "size": 10768,
  "vsize": 3156,
  "version": 1,
  "locktime": 104,
  "vin": [
    {
      "txid": "389ced8ee87ebead8c4c3af49dc86be7e8f543ae3ca6956e319dee180e3a73f4",
      "vout": 26,
      "scriptSig": {
        "asm": "",
        "hex": ""
      },
      "sequence": 4294967293
    },
    {
      "txid": "140e5c0b6254efda8f45428f8ce59c234f92ffa18927fa93169f37158852c26b",
      "vout": 1,
      "scriptSig": {
        "asm": "304502210099e20f146f8294954f7e218f352668a6459ec606c7359209a178ce84f8c5ee8e02200f1dfc39e4ad289b940bddcf07603015427a1ef007a8963006868d40cd94eddd[ALL] 02389c77ce028542467eb93881d7a5a69ba8da99f3bef77da186a45afdfe83a96a",
        "hex": "48304502210099e20f146f8294954f7e218f352668a6459ec606c7359209a178ce84f8c5ee8e02200f1dfc39e4ad289b940bddcf07603015427a1ef007a8963006868d40cd94eddd012102389c77ce028542467eb93881d7a5a69ba8da99f3bef77da186a45afdfe83a96a"
      },
      "sequence": 4294967293
    }
  ],
  "vout": [
    {
      "value-minimum": 0.00000001,
      "value-maximum": 10995.11627776,
      "ct-exponent": 0,
      "ct-bits": 40,
      "assetcommitment": "0a35dfaed9426a4ec0135c76666c1d8b19f98c387d0f5ef4fdba2b1fd93ad2ea52",
      "serValue": "095dbf57592422261c38a1a74afdbddc8737aadda3f14354f83c7bb8228259f6ac",
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 583c205b5d2569697bd237876619397610c2991e OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914583c205b5d2569697bd237876619397610c2991e88ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "2dhUHt49QgLKdxrKUYno7aukKSVf4HEDc4A"
        ]
      }
    },
    {
      "value-minimum": 0.00000001,
      "value-maximum": 1374.38953472,
      "ct-exponent": 0,
      "ct-bits": 37,
      "assetcommitment": "0b39f7e78edc1b7e406b848a7f183f66e0fc1903edf4ba96c666b7a19a47571a18",
      "serValue": "092df9b281d3f9955a86cd7879679365ea9de8c0a5e190cfeb57450123256f8b56",
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 259cac2e43aeccff84d11d31cabb9d5dbf5fa5c4 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914259cac2e43aeccff84d11d31cabb9d5dbf5fa5c488ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "2dcrd5RDbA3W8xKV5H2vaeMse6KQWKqo6Bg"
        ]
      }
    },
    {
      "value-minimum": 0.00000001,
      "value-maximum": 351843.72088832,
      "ct-exponent": 0,
      "ct-bits": 45,
      "assetcommitment": "0b271be9c9e408ef0d7372ee3c62f40212a94e91280ba5680ddc522ad1d6bc5b41",
      "serValue": "09d3e328c4074162cf7a54fbd523343593541d07f2ee4001ba8f4184cf0f76e509",
      "n": 2,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 f044a1bf17b0bceeff136335df73a6874c68a444 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914f044a1bf17b0bceeff136335df73a6874c68a44488ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "2dwLAnBSLKU4Ls8SE6pr6pH1JMAwrtUMXau"
        ]
      }
    },
    {
      "value": 0.00063120,
      "asset": "09f663de96be771f50cab5ded00256ffe63773e2eaa9a604092951cc3d7c6621",
      "serValue": "01000000000000f690",
      "n": 3,
      "scriptPubKey": {
        "asm": "",
        "hex": "",
        "type": "fee"
      }
    }
  ]
}

➜  src git:(elements-0.13.1) ✗ ./elements-cli -regtest -datadir=a getreceivedbyaddress 2dhUHt49QgLKdxrKUYno7aukKSVf4HEDc4A
{
  "f9e41aa0fe764b3dd10fff7602ea91531b75c7285df63d239292657732ae9063": 9000.00000000
}

➜  src git:(elements-0.13.1) ✗ ./elements-cli -regtest getreceivedbyaddress 2dcrd5RDbA3W8xKV5H2vaeMse6KQWKqo6Bg
{
  "f9e41aa0fe764b3dd10fff7602ea91531b75c7285df63d239292657732ae9063": 1000.00000000
}
➜  src git:(elements-0.13.1) ✗ ./elements-cli -regtest -datadir=a getreceivedbyaddress 2dwLAnBSLKU4Ls8SE6pr6pH1JMAwrtUMXau
{
  "bitcoin": 209999.99936880
}
```

**Comment by jonasnick** [comment]
@kallewoof I wasn't saying that you're wrong or something like that. I was just saying that when you send `1000` of some asset, right now you actually send `10,000,000,000` base units ("satoshis" in the case of Bitcoin) which is why the max value is adjusted. For most assets you don't really need precision that high. You could represented 1 of your asset with 100 base units or something, then send `0.001` instead of 1000. However, this looks like a bad UI we need to fix.

**Comment by kallewoof** [comment]
Yeah, no worries, I got that. This is why exponent/mantissa trick or per-asset config of what 1.0 is is needed. Coding software to say that 1 = 0.0000001 is a bit clunky and possibly a bit error prone too. (Hello rounding errors.)

**Comment by jtimon** [comment]
> Ideally though I guess we want to user-define the precision on a per asset basis so we can say that 100 "kalle-satoshis" is 1 "kallecoin".

Right, at some point I would like all rpc calls to just use satoshis/minimal_units instead of 8 decimals. Although this may be happen too slowly upstream or maybe never happen for old calls...

**Comment by instagibbs** [comment]
This will be passively be fixed with bulletproofs
