### ISSUE TITLE
MacOSX instructions overwrite bitcoin.conf

### ISSUE THREAD

**Issue by ChristopherA** [ElementsProject/elements#176]
The installation instructions in https://github.com/ElementsProject/elements/blob/elements-0.13.1/doc/build-osx.md create a bitcoin.conf in the default mac bitcoin directory, which will overwrite one there if someone has already installed bitcoin. At minimum the doc should be changed to warn. Longer term, Elements directory default for mac should not be the same dir as bitcoin.

**Comment by instagibbs** [comment]
Thanks, for now the text should just be changed to `elements.conf`

**Comment by instagibbs** [comment]
https://github.com/ElementsProject/elements/pull/177 Please confirm this fixes the specific issue.
