### ISSUE TITLE
reindex.py test fails in pull-tester suite

### ISSUE THREAD

**Issue by tdudz** [ElementsProject/elements#181]
reindex.py in the qa pull-tester tests fails with an unexpected exception caught during testing.  The bitcoind daemon exits with status -11

**Comment by instagibbs** [comment]
I cannot reproduce locally. Make sure to wipe your local `cache` dir and make sure there are no zombie processes, sometimes those can cause issues.

**Comment by tdudz** [comment]
andrew was able to reproduce the failure on his laptop earlier today. will investigate more tomorrow

**Comment by tdudz** [comment]
Just ran the test suite on a mac and am unable to reproduce the failure. Linux still failing however

**Comment by instagibbs** [comment]
I'll need someone to run in gdb mode, get a stack trace, etc.

**Comment by tdudz** [comment]
is now working fine (in elements 14 rebase), was probably some sort of zombie process from the daemon
