### ISSUE TITLE
Mempool import fails

### ISSUE THREAD

**Issue by kallewoof** [ElementsProject/elements#207]
### Describe the issue

When stopping Elements (regtest) using ^C, after restarting it, mempool transactions will fail to import (possibly because a lot of them are chained and depend on each other).

### Expected behaviour
A ^C shutdown followed by a restart should not fail to import any mempool transactions.

### Actual behaviour
A restart results in a failure to import some/all mempool transactions.

### What version of bitcoin-core are you using?
elements-0.14.1

### Any extra information that might be useful in the debugging process.

```
2017-07-11 11:29:23 Imported mempool transactions from disk: 0 successes, 5 failed, 0 expired
```

**Comment by instagibbs** [comment]
Can confirm the issue, getting the issue when mempool is larger than 1.

**Comment by instagibbs** [comment]
It seems to just be a race between the wallet re-submitting the transaction successfully and being loaded from the mempool cache from disk. Can you make sure that your mempool is actually empty?

**Comment by kallewoof** [comment]
```
$ ./elements-cli -regtest getrawmempool
[
]
```

**Comment by instagibbs** [comment]
resolved https://github.com/ElementsProject/elements/pull/210 and https://github.com/ElementsProject/elements/pull/211
