### ISSUE TITLE
Missing CHECKMULTISIGFROMSTACK

### ISSUE THREAD

**Issue by maaku** [ElementsProject/elements#227]
Now that Schnorr multi-signature aggregation has been removed, there is a need for a MULTISIG version of CHECKSIGFROMSTACK. This was not included in Alpha because Schnorr signatures allowed any multi-sig to reduce to a regular CHECKSIG.

**Comment by instagibbs** [comment]
MuSig deployment in future I think deprecates any real need for this. Closing for now.
