### ISSUE TITLE
windows build failure

### ISSUE THREAD

**Issue by mclycan** [ElementsProject/elements#23]
I have all the dependencies for bitcoind installed and successfully built it in windows(can build bitcoin-qt in windows successfully), but when trying to build alpha it fails with the following error:
CXXLD  alpha-tx.exe
c:/deps/openssl-1.0.1l\libssl.a(ssl_err2.o):ssl_err2.c:(.text+0x4): undefined reference to `ERR_load_crypto_strings'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x1e6): undefined reference to`COMP_CTX_free'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x202): undefined reference to `COMP_CTX_free'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0xa2a): undefined reference to`BIO_s_socket'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0xb25): undefined reference to `BIO_s_socket'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0xc95): undefined reference to`BIO_s_socket'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x1460): undefined reference to `COMP_CTX_free'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x147c): undefined reference to`COMP_CTX_free'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x1580): undefined reference to `COMP_CTX_free'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x159c): undefined reference to`COMP_CTX_free'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x309a): undefined reference to `COMP_CTX_free'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x30b6): more undefined references to`COMP_CTX_free' follow
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x5ca1): undefined reference to `BIO_f_buffer'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x5f9c): undefined reference to`X509_STORE_set_default_paths'
c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o):ssl_lib.c:(.text+0x5fac): undefined reference to `X509_STORE_load_locations'
c:/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: c:/deps/openssl-1.0.1l\libssl.a(ssl_lib.o): bad reloc address 0x80 in section`.data'
c:/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.2/../../../../i686-w64-mingw32/bin/ld.exe: final link failed: Invalid operation
collect2.exe: error: ld returned 1 exit status
make[2]: **\* [alpha-tx.exe] Error 1
make[2]: Leaving directory `/c/elements-alpha/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory`/c/elements-alpha/src'
make: **\* [all-recursive] Error 1

**Comment by gwillen** [comment]
It seems like the problem may be the libssl.a is unable to find symbols in (at least) libcrypto.a (see e.g. http://stackoverflow.com/questions/27106580/undefined-reference-to-err-load-crypto-strings for a linux user having a similar problem.) This could be as simple as the order of the libraries being wrong in a Makefile somewhere.

I've run into similar errors on OS X with parts of the build. It's not unlikely that the build may be legitimately broken on Windows. I will see what I can find but I do not have a machine with mingw to try this out on.

I would try editing `src/Makefile` and swapping the order of the references to `$(CRYPTO_LIBS)` and `$(SSL_LIBS)` on lines 1653-4. So you should end up with:

    $(SSL_LIBS) \
    $(CRYPTO_LIBS)

That _should_ fix at least part of the problem, but for all I know it may cause other problems. I don't know why it's in reverse order as compared to the list for `alpha_cli` just a few lines above, but it's suggestive that it may have been swapped to fix some _other_ link-dependency problem.

**Comment by apoelstra** [comment]
I had a similar problem with my home-built SSL. My hacky way of fixing it without editing any build files was to have `-lcrypto` in `CRYPTO_LIBS` *as well as* `-lssl -lcrypto` in `SSL_LIBS`.

This accomplishes the same goal as @gwillen's suggestion, having `-lcrypto` after `-lssl`, and does not seem to cause any other issues.

**Comment by mclycan** [comment]
@gwillen @apoelstra Thanks for help me! but I have tried this method before, It not work. 
And I found an other issue which I missed before: PKG_PROG_PKG_CONFIG: command not found.
So I will let you knew if I have some progress. Thanks again!

**Comment by gwillen** [comment]
@mclycan: Can you also post the errors you get when you try @apoelstra's method? (It should be at least as good as mine.) That might give us more clues.

The PKG_PROG_PKG_CONFIG error suggests that you don't have `pkg-config` installed. I don't know if there's a "building for Windows" guide, but you can look through https://github.com/bitcoin/bitcoin/blob/master/doc/build-unix.md and see if you've got all the dependencies listed in there?

If you do have `pkg-config`, it could be an insufficiently new version, or it could be some other issue (paths, or a `Makefile` problem on our part.)

(It would also be helpful to see that error in context as well. If there's too much output to put in a comment here, put it into a pastebin, set it to never expire, and paste it here.)

**Comment by mclycan** [comment]
@gwillen  the errors I get are exactly the same as I post before.
And I am try to install "pkg-config" for the msys.
BUT, I can build alpha successfully in OSX, without "pkg-config", which is very strange.

**Comment by jspri3** [comment]
@mclycan Any luck with the windows build? I would like to try the build if someone has been successful here?

**Comment by btcdrak** [comment]
@jspri3 FWIW the best way to build for Windows is using the gitian build process [here]https://github.com/ElementsProject/elements/blob/alpha/doc/gitian-building.md).
