### ISSUE TITLE
Issued asset vanishes due to chain tx limit if too many sent

### ISSUE THREAD

**Issue by kallewoof** [ElementsProject/elements#237]
If you issue an asset and then send it out multiple times without generating a new block, you will eventually hit the mempool chain limit and the asset will completely disappear from your balance.

Generating will not bring it back. Instead you have to wait some time and it will just magically reappear. I believe this is related to recent code where chained transactions would be kept out of the mempool but still be retained, but not sure.

To reproduce:
```Bash
$ mkdir aa
$ ./elementsd -datadir=aa -regtest &
$ alias ecli="./elements-cli -datadir=aa"
$ ecli generate 100
$ ecli issueasset 1000 10
$ ecli getbalance
{
  "bitcoin": 20999999.99912240,
  "f493ec4801feb008965d5182c41dfb24c7daa1e55c46fbd425ed07f25bbec76b": 10.00000000,
  "ff36d716e0b860244385a735b0c99648f15b42939508a82ec517179305ca70b8": 1000.00000000
}
$ asset=ff36d716e0b860244385a735b0c99648f15b42939508a82ec517179305ca70b8
$ addr=$(ecli getnewaddress)
$ for i in $(seq 1 30); do ecli -regtest sendtoaddress $addr 1 "" "" false $asset; done
# last one should get "insufficient funds" error; if not, keep sending; i believe the 30th will get the error
$ ecli getbalance
{
  "bitcoin": 19950000.00000000,
  "f493ec4801feb008965d5182c41dfb24c7daa1e55c46fbd425ed07f25bbec76b": 10.00000000
}
# the asset is now gone completely even though we have 970 left
$ ecli generate 1
$ ecli getbalance
{
  "bitcoin": 19950000.00000000,
  "f493ec4801feb008965d5182c41dfb24c7daa1e55c46fbd425ed07f25bbec76b": 10.00000000
}
$ ecli generate 1
{
  "bitcoin": 19950000.00000000,
  "f493ec4801feb008965d5182c41dfb24c7daa1e55c46fbd425ed07f25bbec76b": 10.00000000
}
...
```

**Comment by instagibbs** [comment]
Yes this is just how sending works with too-long chaining. Over time your wallet will rebroadcast, or you can call some hidden rpc call(`rebroadcasttransactions`?).

**Comment by kallewoof** [comment]
Feels like generate should do that automatically if chaining causes this problem.

**Comment by kallewoof** [comment]
Or a new block incoming in case of e.g. federated block signed chains.

**Comment by instagibbs** [comment]
I don't think generate(or new block) triggers wallet rebroadcast immediately. Probably has privacy implications?

**Comment by kallewoof** [comment]
Hum. But this is sending to/from itself. Why would it not tell itself about its own tx immediately?

**Comment by kallewoof** [comment]
Upstream: https://github.com/bitcoin/bitcoin/pull/11019

**Comment by instagibbs** [comment]
Closing this issue due to it being an upstream one.
