### ISSUE TITLE
Pending errors in travis:

### ISSUE THREAD

**Issue by jtimon** [ElementsProject/elements#241]
Update: see https://github.com/ElementsProject/elements/issues/241#issuecomment-325057851

OLD:
- [X] jni.h: No such file or directory
```
In file included from src/java/org_bitcoin_NativeSecp256k1.c:4:0:
src/java/org_bitcoin_NativeSecp256k1.h:2:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
```
- [X] modules/generator/tests_impl.h: No such file or directory
```
  CC       src/exhaustive_tests-tests_exhaustive.o
src/tests.c:4463:43: fatal error: modules/generator/tests_impl.h: No such file or directory
 # include "modules/generator/tests_impl.h"
```
- [X] Mempool sync failed in listtransactions.py
```
  File "/home/travis/build/ElementsProject/elements/build/elements-i686-pc-linux-gnu/qa/rpc-tests/listtransactions.py", line 43, in run_test
    self.sync_all()
```
- [x] No rule to make target `qt/bitcoin-qt'
- [X] can't build elementsd on ubuntu:16.04 without libdb4.8-dev libdb4.8++-dev installed

I can't build elementsd on ubuntu:16.04 without libdb4.8-dev libdb4.8++-dev installed.
I'm using docker, with the image ubuntu:16.04, I'm installing the following apt packages:
```make build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libminiupnpc-dev libzmq3-dev```

I'm using:
```./configure --disable-wallet --without-gui --with-incompatible-bdb```

This works just fine for bitcoin/master

**Comment by instagibbs** [comment]
What error are you getting?

**Comment by jtimon** [comment]
Oops, sorry: 
```
In file included from ./wallet/walletdb.h:11:0,
                 from ./wallet/wallet.h:19,
                 from rpc/mining.cpp:25:
./wallet/db.h:21:20: fatal error: db_cxx.h: No such file or directory
compilation terminated.
```

**Comment by instagibbs** [comment]
Seems related to build failure here: https://travis-ci.org/ElementsProject/elements/jobs/260867338#L2051

**Comment by jtimon** [comment]
Testet that https://github.com/ElementsProject/elements/pull/229/commits/2141c9c82490a4dcd03f400ac35068ab59026094 in #229 fixes this (at least on my docker setup) and it seems to have fixed it in travis too.

**Comment by instagibbs** [comment]
Can you note which specific builds these errors occur in?

Might be note-worthy.

**Comment by instagibbs** [comment]
Mac error(QT error) is probably due to us not having some private binary for Mac builds. Might not be worth tracking down after talking to Greg.

**Comment by instagibbs** [comment]
Current tip of PR is getting this error for almost all the builds
>bitcoind.cpp:7:35: fatal error: config/bitcoin-config.h: No such file or directory
> #include "config/bitcoin-config.h"

**Comment by instagibbs** [comment]
Ok that was a typo causing all that. Fixed.

Windows and main linux build are passing all tests.

Rest are jni errors or Mac QT.

**Comment by jtimon** [comment]
Summary of current status: 2 builds commented in https://github.com/ElementsProject/elements/blob/elements-0.14.1/.travis.yml#L32

Apparently the mac one needs some special proprietary binary, so I wouldn't hold my breath for it (who uses mac anyway these days? </review_flamer>). Fixing the other one would be pretty nice but we were kind of lost and wanted to have CI tests already.

**Comment by jtimon** [comment]
Travis has been working for a while, we just forgot to close this.
