### ISSUE TITLE
minor: sendtoaddress documents the wrong default for the seventh parameter

### ISSUE THREAD

**Issue by howard-stearns** [ElementsProject/elements#283]
https://github.com/ElementsProject/elementsbp-api-reference/blob/master/api.md#sendtoaddress documents a seventh parameter for "whether to allow unblinded outputs".

The parameter works correctly (I think), but it appears to default to true, while the documentation says it it defaults to false.

**Comment by instagibbs** [comment]
Thank you, I'll open an issue on the documentation-side

**Comment by howard-stearns** [comment]
coolio. thanks.
