### ISSUE TITLE
peg in requires the funds to start on the side chain

### ISSUE THREAD

**Issue by howard-stearns** [ElementsProject/elements#285]
### Describe the issue

The working assets_tutorial.py example shows that funds are "locked up" from the elements side chain (e1.sendtomainchain(bitcoin.getnewaddress(), <locked_sidechain_amount>)) at the start of pegging. This is contrary to the idea that funds initiate on the main chain.

In fact, if that initial locked_sidechain_amount is less than the later bitcoin.sendtoaddress(addrs["mainchain_address"], <claimed_mainchain_amount>) plus a transaction fee, the example will fail.

An example use case would be where one wants to fire up a production sidechain on demand, for an arbitrary amount of funds that an entity has on the mainchain.

I don't know whether this is a bug or a misreading on my part of the sidechain concept and paper. Conversation starting 5:53pm pdt on 10/25 in sidechains.slack.com#technical suggests it is a bug.

#### If so, please list the steps to reproduce below:
1. Run contrib/assets_tutorial/assets_tutorial.py. It works. (see extra info  at end)
2. Increase the amount in txid = bitcoin.sendtoaddress(addrs["mainchain_address"], 1) (line 442) to be the same or greater than the amount locked up (50) on line 426.
3. OR, leave line 442 alone and decrease the amount locked up on line 426 to be the same or less then the amount on line 442 plus transaction fee.

### Expected behaviour
Tell us what should happen
Should work, because you shouldn't need to already have the funds on the sidechain. 

### Actual behaviour
In step 2, the bitcoin.sendtodaddress will fail with "Error: This transaction requires a transaction fee of at least 0.0000312 (-4)" or "Insufficient funds (-6)", depending on how much the amounts differ.

In step 3, the claimtxid = e1.claimpegin(raw, proof, addrs["sidechain_address"]) (line 451) fails with "Failed to find inputs with sufficient value - are you sure bitcoinTx is valid? (-8)"

### What version of bitcoin-core are you using?
Elements Core Daemon version v0.14.1.0-b2bbc67e9-dirty

### Machine specs:
- MacBook Pro, mid 2014

### Any extra information that might be useful in the debugging process.
To get the example to run on my MacBook Pro, I had to increase the various sleep calls.

The example is also missing one bit of cleanup. It should have a very last line of:
shutil.rmtree(b_datadir)

**Comment by instagibbs** [comment]
The whitepaper AFAIK doesn't go into great detail how exactly the funds will be pegged in at a representation level. The code up until now represented those coins explicitly using a script that is only unlocked via proper peg-in proof. Logically speaking it doesn't matter exactly where the coins "come from", only that users cannot access them without proper proofs.

Do note that this is being deprecated for something perhaps more along the lines of what you were originally thinking: https://github.com/ElementsProject/elements/pull/260

**Comment by instagibbs** [comment]
closing for now, since I think this is just a conceptual question
