### ISSUE TITLE
Bug: getrawtransaction no longer return txs in genesis block

### ISSUE THREAD

**Issue by jtimon** [ElementsProject/elements#303]
The genesis txs are no longer returned by getrawtransaction, not even with -txindex, it used to do it for commit https://github.com/ElementsProject/elements/commit/4ff073fa50a6ae3b373282117c56d3faf5c250ec

**Comment by instagibbs** [comment]
Doesn't appear bitcoind allows this either.

**Comment by jtimon** [comment]
Yeah, bitcoin doesn't allow it because the outputs in the genesis block cannot be spent, but in elements we can and thus these txs can be real inputs for other transactions (and since this used to work, it should be only a matter of recovering some old code we had).

**Comment by jtimon** [comment]
Regarding the solution, yeah, that would work, but I'm not sure about what means to undesired dependencies for chainparams.cpp. I don't think that's how we did it before.

**Comment by instagibbs** [comment]
An additional call would just be added early on in ConnectBlock, no new dependencies.

**Comment by jtimon** [comment]
Fixed by https://github.com/ElementsProject/elements/pull/304
