### ISSUE TITLE
Bad invocation of 'git rev-list' during alphad build

### ISSUE THREAD

**Issue by gwillen** [ElementsProject/elements#31]
When building alphad, in the middle of the build process I get the following output:

... (some output, and then:)

```
  CXX      compat/libbitcoin_util_a-glibc_sanity.o
  CXX      compat/libbitcoin_util_a-glibcxx_sanity.o
  CXX      libbitcoin_util_a-chainparamsbase.o
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
  CXX      libbitcoin_util_a-clientversion.o
  CXX      libbitcoin_util_a-random.o
  CXX      libbitcoin_util_a-rpcprotocol.o
```

... (and then some more output)

@gmaxwell is also seeing this, and thought it was due to his old version of Git. But I'm on git 2.3.6 on OS X, and he's on git 2.0.something on Linux, and we're both seeing the same thing. The offending call to `git rev-list` is inside `share/genbuild.sh`. I may take a closer look.

**Comment by sipa** [comment]
Fixed in Bitcoin recently, I believe.

**Comment by gwillen** [comment]
Indeed, this is fixed in https://github.com/bitcoin/bitcoin/commit/c1149f73714a47139cce0d93e92e6b871905b0a1 , and the solution is to hide the message (the error is harmless). I'll bring that over.
