### ISSUE TITLE
make check FAIL : PaymentServerTests::paymentServerTests() Compared values are not the same

### ISSUE THREAD

**Issue by howard-stearns** [ElementsProject/elements#336]
OSX 10.13.4, MacBook Pro (Retina, 15-inch, Mid 2014) 16GB i7.
elements-0.14.1 commit f6e211de5553c5b10cc7e090c5abed60caee0861
make check fails qt/test/test_elements-qt

I will include config.log and test-suite.log, of which the latter reports:
FAIL!  : PaymentServerTests::paymentServerTests() Compared values are not the same

**Comment by howard-stearns** [comment]
[config.log](https://github.com/ElementsProject/elements/files/1929300/config.log)
[test-suite.log](https://github.com/ElementsProject/elements/files/1929301/test-suite.log)

**Comment by instagibbs** [comment]
QT is completely unmaintained, but a simple fix to have it pass wouldn't be harmful.

**Comment by howard-stearns** [comment]
ah, so if I'm just using elementsd, then there's no problem?

**Comment by instagibbs** [comment]
correct, I had thought we were make checking with qt, so like I said would accept a "fix"

**Comment by instagibbs** [comment]
no problem
