### ISSUE TITLE
decodescript still says OP_NOP3, not OP_CSV

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/elements#35]
alpha-cli -datadir=/home/rusty/.alpha -regtest -testnet=0 decodescript 748c63a9148ffaeae14cbffc20dd8d5bd948a61e9acf9af4cf882102ba9e8a913c675861d8b9a8ca3020a1b615f391500e668cd799a2b3cf59c5789267043c65cd1db2752102949f823b49795c9a86d8d60493cafe9b7542b4a4b2f14b3d04214ef6eaf1e05068ac
{
    "asm" : "OP_DEPTH OP_1SUB OP_IF OP_HASH160 8ffaeae14cbffc20dd8d5bd948a61e9acf9af4cf OP_EQUALVERIFY 02ba9e8a913c675861d8b9a8ca3020a1b615f391500e668cd799a2b3cf59c57892 OP_ELSE 500000060 OP_NOP3 OP_DROP 02949f823b49795c9a86d8d60493cafe9b7542b4a4b2f14b3d04214ef6eaf1e050 OP_ENDIF OP_CHECKSIG",
    "type" : "nonstandard",
    "p2sh" : "2N1SwkKGpJBViUgi147sT2cjyS5pMPEb8so"
}

**Comment by instagibbs** [comment]
hopefully fixed after 3+ rebases onto Core
