### ISSUE TITLE
Rebuild the database using -reindex to change -txindex.

### ISSUE THREAD

**Issue by sweyn** [ElementsProject/elements#36]
Already running bitcoind binary, checked out alpha and compiled. On launching bitcoind, I am prompted to rebuild the block database:

< quote>

$:bitcoind -rpcuser=$RPC_USER -rpcpassword=$RPC_PASS -testnet -txindex -daemon
Bitcoin server starting
$:: You need to rebuild the database using -reindex to change -txindex.

Do you want to rebuild the block database now?

< end quote>

Is this necessary for elements or an artefact of not building bitcoind from source? 

(On Ubuntu 14.04 64)

**Comment by sipa** [comment]
This is a result of starting Alpha first without -txindex index, and then
wanting to turn it on. This is no different from bitcoins.

**Comment by sweyn** [comment]
Alpha is not running when this message appears. How do you suggest resolving? By reindexing?

**Comment by sipa** [comment]
When you first started alpha, it created a non-txindex database. You can
only change to a yes-txindex database at initial creation (or the index
would be missing old parts).

Yes, start with -reindex (only once) will fix it.

**Comment by sweyn** [comment]
-reindex for bitcoind completed, thanks, both for the main blockchain and testnet (presumably there are different txindex files for Bitcoin and testnet, please correct if this understanding is wrong). 

If txindex=1 in bitcoin.conf, is -txindex redundant from options for alphad? Or is it necessary to explicitly invoke -txindex for alphad? Does alphad read bitcoin.conf or have a comparable conf file?

**Comment by jtimon** [comment]
You shouldn't reuse the same conf file for the 2 programs but it is technically possible.
Closing as it seems there's nothing to fix.

**Comment by SaxoBeatMos** [comment]
Так и не решается проблема с запуском клиента командой -txindex? при запуске пишет
 You need to rebuild the database using -reindex to change -txindex.
запускаю -reindex-chainstate все индексируется, после этого пробую запустить -txindex и опять пишет переиндексируйте
