### ISSUE TITLE
Cannot change default initial asset issuance label from 'bitcoin'

### ISSUE THREAD

**Issue by wintercooled** [ElementsProject/elements#371]
It would be nice for those creating stand alone blockchain implementations to be able to use a new parameter in conjunction to 'initialfreecoins' called something like 'defaultassetname' or something that allowed you to overwrite the 'bitcoin' label that is defaulted to.

Scenario - someone wants to use Elements to set up a standalone blockchain with 10M amount of a native asset called 'newasset'. Currently they must issue some of the default 'bitcoin' asset in order to fund a tx that creates 'newasset'. Then you can set -feeasset to newasset - which is fine - but in order for subsequent nodes to 'see' newasset's issuance they also need initifialfreecoins set to > 0 so that they are aware of the 'bitcoin' asset that was used to fund the asset creations. Which ends up being a bit of a 'work around'.

Other things to consider - can you reissue the default created asset to create more of them? Might be needed if you go down the route above. Currently I think this is not the case.

**Comment by instagibbs** [comment]
`-initialfreetokens` or something would be quite easy to implement for reissuance purposes.

**Comment by wintercooled** [comment]
Good idea. Will look at this - starting in assetsdir.cpp. 
Aim is to enable initialfreetokens (or something) to be set and a non-bitcoin asset to be created on initial issuance and also enable that to be reissued when needed.

**Comment by wintercooled** [comment]
-initialreissuancetokens requires changes to:
chainparams.h (declaration) 
chainparams.cpp (set using new param, pass to AppendInitialIssuance)
init.cpp (help message)

Working on this now.

**Comment by wintercooled** [comment]
This was affected by Issues #355 and #378. 355 should fix 378 and allows me to continue with the change to be able to set the default asset to something other than 'bitcoin'.

**Comment by wintercooled** [comment]
Recent issues being fixed (see last comment) allows my changes for this to run ok now. Will PR today hopefully.

**Comment by wintercooled** [comment]
PR #384 addresses this.

**Comment by wintercooled** [comment]
Closing as this has been addressed with merged PR #384
