### ISSUE TITLE
Method not found on RPC call sidechain-manipulation.py

### ISSUE THREAD

**Issue by Christewart** [ElementsProject/elements#38]
Hi everyone, I'm following the [alpha-readme.md](https://github.com/ElementsProject/elements/blob/alpha/alpha-README.md) for getting started with sidechains. I am on step 6. I'm trying to run this command 

chris@chris-870Z5E-880Z5E-680Z5E:~/dev/elements$ ./contrib/sidechain-manipulation.py generate-one-of-one-multisig sidechain-wallet
Traceback (most recent call last):
  File "./contrib/sidechain-manipulation.py", line 95, in <module>
    address = sidechain.getnewaddress()
  File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 138, in __call__
    raise JSONRPCException(response['error'])
JSONRPCException: -32601: Method not found

Got the following error from an RPC Call:
{u'message': u'Method not found', u'code': -32601}

but I am getting an error instead of a response like the guide indicates. I'm not familiar with what this error is. I'm pretty sure I have followed all of the steps in the guide. Is anyone familiar with this?

**Comment by droark** [comment]
Hello. I'm guessing that, for some reason, the Bitcoin JSON code isn't properly installed. Can you confirm that you've followed the directions? If so, I'm not sure what to say.

**Comment by Christewart** [comment]
I'm not sure where this error was coming from. I redid the installation process this morning and everything appears to be working correctly. I think I may have screwed up the BerkleyDB installation process when I first created this ticket.
