### ISSUE TITLE
Append initial issuance to 1 address not 100 breaks tutorial code

### ISSUE THREAD

**Issue by wintercooled** [ElementsProject/elements#380]
#355 means that the tutorial will no longer work as the first send from e1 leaves no funds accessible for e2.

This tutorial: https://github.com/ElementsProject/elements/tree/elements-0.14.1/contrib/assets_tutorial

Could just send all to e1 then get e1 to send half to e2 to fix? Will look into.

**Comment by instagibbs** [comment]
Sounds right. Thanks!

**Comment by wintercooled** [comment]
Looking at fixing this now...

**Comment by wintercooled** [comment]
PR #383 raised to resolve this issue.

**Comment by wintercooled** [comment]
Closed - fixed with #383
