### ISSUE TITLE
run cmd send-to-sidechain get "Insufficient funds"

### ISSUE THREAD

**Issue by software-zjz** [ElementsProject/elements#385]
I'm running cmd:
./contrib/sidechain-manipulation.py  send-to-sidechain   2MtCDfX4sL7QWVwn4MXtrzuTWZk6P12E4fw 1
Sending 1 to 2NCqpdcZcAoC4HoduGQmEZKAaHGtV28K8Si...
(nonce: 2c58572a079358337db6609b3ba87718)
tx_hex: 01000000000100e1f5050000000017a914d6f5739e14eeccab5479fd58c9dd35f6160b408b8700000000
Got the following error from an RPC Call:
{u'message': u'Insufficient funds', u'code': -32603}
Traceback (most recent call last):
  File "./contrib/sidechain-manipulation.py", line 199, in <module>
    txid = bitcoin.sendtoaddress(send_address, Decimal(args.coinAmt))
  File "/root/elements/contrib/../../python-bitcoinrpc/bitcoinrpc/authproxy.py", line 141, in __call__
    raise JSONRPCException(response['error'])
JSONRPCException: -6: Insufficient funds

Got the following error from an RPC Call:
{u'message': u'Insufficient funds', u'code': -6}

but, i have funds in 2MtCDfX4sL7QWVwn4MXtrzuTWZk6P12E4fw,what error is it? thanks!

**Comment by instagibbs** [comment]
Which branch are you running? That looks like alpha, which is no longer supported.

**Comment by software-zjz** [comment]
thank you for my question,i use that https://github.com/ElementsProject/elements/blob/alpha/alpha-README.md

**Comment by software-zjz** [comment]
thank you for my question,i use that https://github.com/ElementsProject/elements/blob/alpha/alpha-README.md

**Comment by instagibbs** [comment]
Right, please use the `elements-0.14.1` branch in the future.

**Comment by software-zjz** [comment]
the version must be elements-0.14.1,but i get "Insufficient funds" error,please help me,thanks!

**Comment by software-zjz** [comment]
then,please give me good idea,thanks!

**Comment by software-zjz** [comment]
dear instagibbs , Elements -0.14.1 must be used to validate side chain technology, I seem to understand a little, thank you!
