### ISSUE TITLE
sendtoaddress and sendmany default to 'bitcoin' asset

### ISSUE THREAD

**Issue by wintercooled** [ElementsProject/elements#395]
If you do not specify an asset then sendtoaddress and sendmany default to trying to send 'bitcoin', which may not be a known asset if the "defaultpeggedassetname" param has been provided a value on chain initialisation.

This makes the two functions a bit less intuitive as you have to use:

elements-cli sendtoaddress someaddresshere 1 "" "" true thedefaultassetnamehere

Instead of 

elements-cli sendtoaddress someaddresshere 1 "" "" true

I am looking to makes changes that fix this now.

**Comment by wintercooled** [comment]
Raised PR #396

**Comment by instagibbs** [comment]
was fixed
