### ISSUE TITLE
policyAsset not set in c++ unit tests

### ISSUE THREAD

**Issue by nkostoulas** [ElementsProject/elements#408]
Policy/fee asset doesn't seem to be set in the src/test unit-tests. I noticed this in txvalidationcache_tests.cpp, where the fee output was discarded when the tx was entered in the mempool as in AcceptToMemoryPoolWorker the following returns 0:

`CAmount nFees = tx.GetFee()[policyAsset];`

Although it doesn't break anything as zero fees are allowed, it might hide intended functionality if something changed. Do you think it would make sense to add this in the test_bitcoin configuration?

**Comment by instagibbs** [comment]
yes, thank you

**Comment by instagibbs** [comment]
Do you have a backtrace for the issue?

**Comment by nkostoulas** [comment]
```
FAIL: test/test_elements
========================

Running 210 test cases...
unknown location:0: fatal error: in "tx_validationcache_tests/tx_mempool_block_doublespend": signal: SIGSEGV, si_code: 0 (memory access violation at address: 0x00000000)
test/txvalidationcache_tests.cpp:70: last checkpoint

*** 1 failure is detected in the test module "Bitcoin Test Suite"
Assertion failed: (!pthread_mutex_destroy(&m)), function ~recursive_mutex, file /usr/local/include/boost/thread/pthread/recursive_mutex.hpp, line 104.
FAIL test/test_elements (exit status: 134)
```

Is there a way to get a detailed trace?

**Comment by instagibbs** [comment]
Does your change fix it? That's a good indicator!

**Comment by nkostoulas** [comment]
Yea it does! I was just curious why it was happening.

**Comment by instagibbs** [comment]
We can keep this issue open if you like even if we merge the fix.
