### ISSUE TITLE
alphad maxes out the CPU while waiting for Tx confirmations?

### ISSUE THREAD

**Issue by droark** [ElementsProject/elements#43]
Hello. I'm running Ubuntu 15.04 and am attempting to follow the alpha README. In particular, I'm now trying to move money into alpha ("send-to-sidechain"). I sent a coin, and now alphad is maxing out my CPU. Anybody have any idea why this might be happening? Is it trying to sync with bitcoind somehow? Is there some way I can confirm what's going on? There are a couple of wrinkles that I encountered initially, which might have some bearing. (Doubtful, but hey, I might as well list everything.)
- I was running Armory in testnet mode when I sent the money. The Python script apparently used an Armory wallet, which was interesting, as I had to apply a small hack to the script to unlock the wallet first. ~~(I'd submit a PR to fix this but I'm not sure offhand what the recommended method is to check for a locked wallet before proceeding. I don't see any valid RPC calls.)~~ (PR https://github.com/ElementsProject/elements/pull/44 has been submitted.)
- ~~The Tx had no fees attached. Is this intentional? Is this a byproduct of Armory being used by accident?~~  (Nevermind. Looks like Armory somehow didn't record the fee, possibly because the P2SH input address uses a compressed key. Either that or the block explorer I'm using is lying. :) )

Hmmm. Wait a minute. Now that confirmations are rolling in, alphad has calmed down. Perhaps it gets spun up while waiting for a confirmation? I'll try again and see if it happens again.

Thanks.

**Comment by TheBlueMatt** [comment]
This is quite possibly unrelated - the IP-to-connect-to selection algorithm sucks if there aren't that many nodes available. This may be what you are seeing, and is actually not trivial to fix without fixing addrman in Bitcoin Core itself.

**Comment by droark** [comment]
Thanks, Matt. Is there any relatively simple way to check to see if this is the case? FWIW, when I executed getpeerinfo() while this was happening, I saw three nodes listed.

**Comment by TheBlueMatt** [comment]
Check which thread is using the CPU by pressing "H" in top. The threads should be named something vaguely descriptive.

**Comment by instagibbs** [comment]
extremely filthily old. closing.
