### ISSUE TITLE
[Feature Request] Stop depending on bitcoin-cli

### ISSUE THREAD

**Issue by NicolasDorier** [ElementsProject/elements#438]
It would be nice if there was no dependency on bitcoin-cli.

* It makes a multi arch docker image harder to create as you need to pull out the right binaries
* Because of 0.17.0 having breaking change in configuration, a clightning image can't target at the same time a 0.16.3 node and a 0.17.0 node on something else than mainnet

Because setting up some configuration value for regtest and testnet require a section in 0.17.0, but such section can't be read from 0.16.3 bitcoin-cli tooling. And not using a section on regtest and testnet on 0.17.0 will result in some config parameter which not being properly applied by bitcoind, while it would be applied by bitcoin-cli 0.16.3 tooling.

I really blame core to have messed up so badly with breaking changes in configuration files... It makes bitcoin-cli dependency an even bigger burden.

**Comment by instagibbs** [comment]
Thoughts on what to replace it with? 

The conf breaks are really far and few between(0.17 is kind of annoying though).

**Comment by NicolasDorier** [comment]
The best would be to directly create the RPC requests in code as bitcoin-cli does.

**Comment by stevenroose** [comment]
Exactly which dependency on bitcoin-cli is this about?

**Comment by NicolasDorier** [comment]
@stevenroose  What do you mean? Right now if clightning can't find bitcoin-cli, then clightning does not work.

**Comment by instagibbs** [comment]
Are you attempting to post this in lightning repo?

**Comment by stevenroose** [comment]
Seems like it..

**Comment by instagibbs** [comment]
Closing unless we're reading this wrong :)

**Comment by NicolasDorier** [comment]
shit
