### ISSUE TITLE
Man pages are still named bitcoind, bicoin-cli and bitcoin-tx

### ISSUE THREAD

**Issue by sgeisler** [ElementsProject/elements#439]
### Describe the issue
The man pages in `doc/man/` seem to still be the ones for bitcoin and not the ones for elements.

### Expected behaviour
Include the according elements man pages instead.

### Actual behaviour
The included man pages are for bitcoin 0.14. Depending on the deployment mechanism they might end up overwriting the already installed bitcoin man pages.

**Comment by instagibbs** [comment]
Thanks for the report, sounds like something we'd have to address in gitian builds.

**Comment by instagibbs** [comment]
btw just found where these are defined: https://github.com/ElementsProject/elements/blob/elements-0.14.1/contrib/devtools/gen-manpages.sh

**Comment by stevenroose** [comment]
Should be fixed when https://github.com/ElementsProject/elements/pull/521 is merged.

**Comment by instagibbs** [comment]
resolved in master, closing
