### ISSUE TITLE
elements-0.14.1 branch is using which version of the bitcoin code

### ISSUE THREAD

**Issue by prologic-dev** [ElementsProject/elements#444]
which version of bitcoin code  is merge with the elements-0.14.1 ?

Is the elements-0.14.1 support latest bitcoin code ?

**Comment by instagibbs** [comment]
It's based on Bitcoin Core 0.14 branch. We're working on updating this to 0.17 now.

**Comment by prologic-dev** [comment]
Thanks for the clearification
