### ISSUE TITLE
Offline raw claim peg-in transaction singing errors

### ISSUE THREAD

**Issue by grubles** [ElementsProject/elements#465]
### Describe the issue
I'm trying to claim L-BTC on Liquid using one online `liquidd` and one offline. When attempting to sign a raw claim peg-in transaction generated with `createrawpegin`, the signing errors with `Peg-in input has invalid proof.` My setup is as follows: 

`bitcoind` and `liquidd` running online on one computer.

`bitcoind` and `liquidd` running offline on a separate computer. 

### Can you reliably reproduce the issue?
Yes.

#### If so, please list the steps to reproduce below:
1. Gather claim_script and BTC peg-in raw transaction 
2. Generate `txoutproof` with online `bitcoind`
3. Use `createrawpegin` with above information
4. Move raw transaction hex to offline `liquidd`
5. Attempt to sign the raw tx with `signrawtransaction`
6. Signing errors

### Expected behaviour
Signing should complete successfully 

### Actual behaviour
Signing errors with "Peg-in input has invalid proof."

### What version of bitcoin-core are you using?
Bitcoin Core 0.17.0 official binary

**Comment by instagibbs** [comment]
are you running `validatepegin=1` on the offline machine?

**Comment by grubles** [comment]
Running with nothing specified defaults to `1` right? I tried with `0` as well and it didn't work.

**Comment by instagibbs** [comment]
@grubles take a look at https://github.com/ElementsProject/elements/pull/466 to see if I am covering the logic you're hitting?

I can't replicate.

**Comment by instagibbs** [comment]
Ok, I think I figured it out. If you don't let the peg-in mature it won't allow you to sign it currently.

I suppose it should allow signing, especially on an offline machine!

**Comment by grubles** [comment]
Turns out I was typo'ing `validatepegin=0` with validatepegin**s**=0. 

When running with `validatepegin=0`, the offline signing completed successfully and returned a `"completed": true"`.

**Comment by instagibbs** [comment]
Great, moving ahead with my PR that should make this issue smoother for offline signing even if fat-fingered.
