### ISSUE TITLE
Need "createrawissuanceinput" raw issuance RPC API

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#471]
Currently there is no "raw" way of doing issuance, which means something like multisig (re-)issuance across different nodes is currently not implemented.

A new call could allow the caller to insert the proper pseudo-input and corresponding output into the designated output script.

**Comment by tomt1664** [comment]
We have implemented raw issuance and re-issuance RPCs on our fork of elements:
https://github.com/commerceblock/ocean/pull/22
https://github.com/commerceblock/ocean/pull/34

They have been designed specifically for our use case so may need some changes to be of more general use. Can open a PR if useful.

**Comment by instagibbs** [comment]
Thanks for the pointer, I've already got something I believe to be working, and a bit more general. Cleaning it up now, but it takes a raw transaction and appends issuances to already-existing inputs as requested.

This way you can `createraw`->`fundraw`->`rawissueasset`->`blindraw`->`signraw`, all without requiring wallet access for the call.

**Comment by instagibbs** [comment]
completed our raw issuance rpc calls

**Comment by tiero** [comment]
Hey, I'm trying to figure out how to use it. There is any unit test/spec where I can see a real example?

**Comment by instagibbs** [comment]
Grep the rpc tests in qa/rpc-tests. There is pretty significant testing
examples.
