### ISSUE TITLE
Race condition with failing bitcoind can result in assertion

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#483]
When the bitcoind falls over after a peg-in transaction has entered the mempool, if a new block(which doesn't include that transaction) arrives, a quick re-check of validity happens of all mempool transactions. When the peg-in validation fails(due to bitcoind being down), it hits an assertion:

`AssertionError: Unexpected stderr bitcoind: txmempool.cpp:645: void CheckInputsAndUpdateCoins(const CTxMemPoolEntry&, CCoinsViewCache&, int64_t, std::set<std::pair<uint256, COutPoint> >&): Assertion `fCheckResult' failed. !=`

Best thing we can do likely is note the failure and log it more explicitly.

We need to make sure that are tests won't hit it in the future however, or that we handle it properly.

**Comment by stevenroose** [comment]
I fixed the test for that. It not shits down sidechains first, then parents.

As for non-test, I think logging would be ok. If the pegin gets spent in another tx, that will evict the tx, right? It's just when the bitcoind goes down? So in fact if the extra bitcoind check was not done, it could only cause problems on a reorg of the parent chain? Since by default we wait for 8 confirmations, that's quite unlikely.

**Comment by instagibbs** [comment]
The test doesn't seem to be fixed. Leaving this open for further investigation.

**Comment by stevenroose** [comment]
I saw it fail again indeed. Not sure it's still this error, though. I made the fedpeg test stop the nodes manually, so I think that exact race condition should not happen again. But yeah clearly something is up.

**Comment by stevenroose** [comment]
It also doesn't help that I really can't cause it to fail on my machine. Ran the fedpeg test non-stop in repeat for half a day and it didn't want to fail.

**Comment by instagibbs** [comment]
https://github.com/ElementsProject/elements/pull/565 this should fix the assert.

**Comment by stevenroose** [comment]
Would it be very bad to just consider the parent check as failed when bitcoind crashes? This would kick the tx from the mempool, but at least not hit the assertion..

**Comment by instagibbs** [comment]
It won't kick it. This assertion is a belt and suspenders check in regtest
like chains only.

**Comment by stevenroose** [comment]
Is this fixed with https://github.com/ElementsProject/elements/pull/565?

**Comment by instagibbs** [comment]
It should be! If another issue pops up we know we have some real logic error.
