### ISSUE TITLE
src/blind.cpp does not have standard license header, like other .cpp files

### ISSUE THREAD

**Issue by dgpv** [ElementsProject/elements#485]
https://github.com/ElementsProject/elements/blob/5467be3b16f014b371ecf6bced73be0254755cfa/src/blind.cpp#L1

Other files have copyright notices and reference to MIT license.

Is the code in blind.cpp also covered under MIT License ?

**Comment by instagibbs** [comment]
It should. Feel free to add as PR!

**Comment by dgpv** [comment]
PR merged, closing.
