### ISSUE TITLE
[brainstorming] git merge strategy for syncing with upstream

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#499]
A single PR should contain a single merge commit in "digestible" chunks. PR title should be prepended by `[<local_branch_name> MERGE]`. Ideally this is done ~once per month. If the merge commit compiles and passes all tests, the merge commit message is prepended with `UPSTREAM MERGE:`. If the resulting merge contains compilation/test failures, the merge commit is prepended by `UPSTREAM MERGE BROKEN:` and these issues should be fixed in separate commits on top, with their commit message prepended `MERGE-FIX:`.

This allows for easy history reading(discrete fixes with clear reasoning), and bisection rules to skip known bad sections.

Example with "clean" merge that passes tests: #500 
Example with "broken" merge that fails a single functional test, with fix appended: #501

**Comment by stevenroose** [comment]
ACK!

**Comment by instagibbs** [comment]
example: https://github.com/ElementsProject/elements/pull/500

**Comment by stevenroose** [comment]
Just mentioning: a pretty decent review strategy for catchup PRs is to do the following:

- `git branch tmp`
- `git merge bitcoin/<to-merge>`
- `git add -u` (adds all tracked files, this leaves the conflicts in the files)
- `git merge --continue`
- `git diff HEAD instagibbs/merge_pr`

Then go over the diff and check only the wrong conflict parts are there, plus any conflict resolution changes.

**Comment by instagibbs** [comment]
Had to sync bitcoin_functional, here was the changelog for adapting to "regtest2" custom chain: https://github.com/ElementsProject/elements/pull/502/commits/9d9ee3d5148ca68155b446468a618ee813bae5c0

**Comment by apoelstra** [comment]
Closing as I think we have a working merge strategy now. Needs documentation, uploaded scripts (and maybe ports to Python?) but these should be covered by another issue.
