### ISSUE TITLE
claimpegin RPC Reference says 10 confirmations needed - is it not 102?

### ISSUE THREAD

**Issue by wintercooled** [ElementsProject/elements#506]
doc/elements-api.md says:

"The mainchain deposit transaction must have at least 10 confirmations before the claim is valid"

Is it not 102 confirmations? or say "the transaction will not be relayed unless it is at least 102 blocks deep" as elsewhere.

**Comment by instagibbs** [comment]
https://github.com/ElementsProject/elements/blob/elements-0.14.1/src/chainparams.cpp#L131 defines it for each network. Elements uses 8, I believe, +2 for wallet to make sure it doesn't go into a race condition with other nodes. Liquid is 100 + 2.

**Comment by wintercooled** [comment]
Ah I see . Thanks, will close and ditch the associated PR. Cheers.
