### ISSUE TITLE
allow dumpblindingkey to accept unconfidential address (when invoked with special flag ?)

### ISSUE THREAD

**Issue by dgpv** [ElementsProject/elements#511]
Right now dumpblindingkey checks that the address that is passed to it is confidential address, and compares the pubkey with the one generated from blinding key.

But sometimes it is not easy to get the confidential address - for example if we want blinding key for the change address, or it is just inconvenient to go find where you recorded the correcponding confidential address when you are looking at the address in getrawtransaction output.

I think allowing to dump a blinding key for any address would be useful for testing/debugging purposes.

**Comment by dgpv** [comment]
Like this:

`
Dumps the private blinding key for a CT address in hex.
Arguments:
1. "address"          (string, required) The CT address
2. nocheck (bool, optional, default=false) Skip checking that blinding pubkey in the address matches the blinding key. Allows to dump blinding key for  non-CT address

> elements-cli dumpblindingkey "my address"
> elements-cli dumpblindingkey "my address" true
 `

**Comment by instagibbs** [comment]
Fwiw validateaddress(getaddressinfo in 0.17) should give you the
confidential version the wallet knows.

**Comment by dgpv** [comment]
I am creating examples for python-bitcointx and just thinkging how to make mini-tutorial for these examples more simple. I think I just won't include the part where you dump the blinding key for the change address to be able to unblind it. Maybe will add this when 0.17 come out.

**Comment by dgpv** [comment]
This will be possible in 0.17, and doing this in two steps would be more correct - as it will catch mistakes when you give it an address that the node does not know. So I am closing the issue
