### ISSUE TITLE
Make sure gitian builds work

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#529]

**Comment by greenaddress** [comment]
I built 6fa39762c3d3fee20cacf6163b755c7b760111b9

7a402ed912b49da0356dff4f461d7f7b66e747875cfe91e3863d179944a525f2  elements-0.17.0-aarch64-linux-gnu-debug.tar.gz
711f03141df2f60c85138ec58f65439ccd0f9bef726692fc9d91e3db5ce33ff2  elements-0.17.0-aarch64-linux-gnu.tar.gz
51a964282597cbea8793ca4fe9baa690ed5375c9d72ca96d6972b0794cde53c6  elements-0.17.0-arm-linux-gnueabihf-debug.tar.gz
ec7accda50a6d36122e8a05ffd985d032b9e5552ffbc61a791e7454dc446d7f0  elements-0.17.0-arm-linux-gnueabihf.tar.gz
604c9a23bad359ba11975fd3aa14239b7b0b1dd534f40c7afab4eddddc97758a  elements-0.17.0-i686-pc-linux-gnu-debug.tar.gz
e4081331a3a4c800432c52e4a208d50bbf8980f36f8096ab09027d03553c5452  elements-0.17.0-i686-pc-linux-gnu.tar.gz
ce05d27d4bbbfcba1ef499dc9ef7a961a08a955ea48c28ed11955c9831027e94  elements-0.17.0-riscv64-linux-gnu-debug.tar.gz
b147eccf3bf8b3e7995e36e8fa4d2da1cd1255c72523ddf8bb2f00e85a145363  elements-0.17.0-riscv64-linux-gnu.tar.gz
3af501c7bdc6d16e987d99d1b29ba378af8fe90c86789e6a2a6bc9e5f78a3d7b  elements-0.17.0-x86_64-linux-gnu-debug.tar.gz
23f5b52f352bb2859bf5bf38341c554a8ee2028b1ee6d595f05ed1877651953d  elements-0.17.0-x86_64-linux-gnu.tar.gz
de50fd5e0b340806cfebe91465c036b0604af5bf3d92345f80e121b8f40918c3  src/elements-0.17.0.tar.gz
baf5a3625c2b7ac081a13c2ec1208bcaeb699abe5fd60b32889d3b83b3e69bce  elements-linux-0.18-res.yml

**Comment by instagibbs** [comment]
Going to wait for post-merge of the rest of the items: https://github.com/ElementsProject/elements/issues/570

**Comment by instagibbs** [comment]
Gitian setups appear to be working
