### ISSUE TITLE
Consensus parameter commitment tracking issue

### ISSUE THREAD

**Issue by apoelstra** [ElementsProject/elements#534]
In the next hardforking change we should add a separate Merkle tree to Elements blocks, committing to

* The Blocksigner policy (`signblockscript`), encoded as a Script
* The Watchman policy (`fedpegscript`), encoded as a Script
* An arbitrary bytestring (which Liquid will use for its PAK list), encoded as a byte vector

We should further change the consensus rules such that whenever 4/5 of the most recent 4320 blocks (30 days of 1-minute blocks) commit to different parameters than the current consensus parameters, the committed parameters become the new consensus rules -- with the exception that peg-ins using the old `fedpegscript` will continue to be recognized for another 4320 blocks to give claimants time to adjust.

**Comment by apoelstra** [comment]
It would also be good to ensure that the new `fedpegscript` policy is capable of satisfying the old one. This is easy to do in the Liquid functionary code which uses Rust and can therefore use rust-miniscript, but might be harder to do in consensus.

**Comment by roconnor-blockstream** [comment]
In the future, when Simplicity is incorporated into Elements, this mechanism could be used to migrate to a new set of discounted Simplicity jets.  Updating the set of discounted jets effectively allows Simplicity effectively migrate to new sets of cryptographic primitives (e.g. post-quantum crypto) as they are developed.

**Comment by gwillen** [comment]
Worth clarifying slightly, although it's sort of implied in what you said: the thing committed is not 'the policy' but 'the proposed policy' according to the functionary creating the block.

Also, drop in a link to the design doc? Or to the PR for it, if it's not in yet?

**Comment by apoelstra** [comment]
The design doc is still in flux. I'll copy the non-Liquid stuff in when it's stable.

**Comment by jonasnick** [comment]
It would be useful if there was also a commitment to the currently active rules because
1. it helps debugging
2. if the transition rules are validated by `hsm_blocksigner` then any verifier (such as hsm_watchman) can check the active rules at a given block without having to implement transition or fork logic themselves.

**Comment by instagibbs** [comment]
Great point ACK

**Comment by instagibbs** [comment]
this issue is resolved via https://github.com/ElementsProject/elements/pull/642
