### ISSUE TITLE
create a raw transaction to burn assets

### ISSUE THREAD

**Issue by dgyoshi** [ElementsProject/elements#557]
I am trying to create a raw transaction to burn assets issued by us. I took a look at the code of createrawtransaction. it cannot produce that. If you set "data output", the amount to burn is "0" because it is hard coded and it is the way to burn asset in bitcoin. And also there is no way to set what asset is burned, the third parameter of it requires address in order to define asset of output.

It would be useful to enhance createrawtransaction to support more elements transaction.

**Comment by instagibbs** [comment]
https://github.com/ElementsProject/elements/pull/558 This may resolve your needs.

**Comment by dgyoshi** [comment]
@instagibbs Yes, it is perfect.
