### ISSUE TITLE
Remove potential signature malleability over issuance inputs

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#559]
Serialization leaves the exact inputs ambiguous, mixing single byte `0` and full `assetIssuance` data in the signature hash: https://github.com/ElementsProject/elements/blob/master/src/script/interpreter.cpp#L1585

This could allow malleability where signatures are replayed on other transactions, though it seems most are prevented by sighash_all and surjection proofs.

A future sighash version could fix this by canonically serializing all the inputs with varints.

**Comment by apoelstra** [comment]
Fixed by #1002
