### ISSUE TITLE
Default address prefixes when started in regtest mode on 0.17

### ISSUE THREAD

**Issue by dgpv** [ElementsProject/elements#567]
in 0.14.1 when you start elements daemon by default the prefixes were 235 for p2phk and 75 for p2sh, now it is 111/196

As said by @instagibbs on #elements slack channel:

> Any chain that isn't main/testnet3/regtest/liquidv1 has the elements defaults whatever those are. Set in chainparams.cpp We should match whatever 0.14 had for consistency sake

**Comment by instagibbs** [comment]
@dgpv should be fixed in #568
