### ISSUE TITLE
elements-qt 0.17: change amount shown in details dialog for assets other than L-BTC

### ISSUE THREAD

**Issue by domegabri** [ElementsProject/elements#580]
#### version

Elements Core version v0.17.0.0-1f67fec0e (release build)

#### description

not reproduced for L-BTC.  Total balance of the asset in question was 500. screenshot attached:

<img width="1200" alt="Screenshot 2019-04-17 at 17 35 28" src="https://user-images.githubusercontent.com/42006886/56302537-42e7dd80-613a-11e9-8019-3f39dc444e71.png">

**Comment by instagibbs** [comment]
cannot replicate currently

**Comment by instagibbs** [comment]
Probably resolved by https://github.com/ElementsProject/elements/pull/574 , he cannot replicate anymore, closing for now
