### ISSUE TITLE
incoming tx notification shown for an outgoing transaction

### ISSUE THREAD

**Issue by domegabri** [ElementsProject/elements#582]
#### version

Elements Core version v0.17.0.0-1f67fec0e (release build)

#### description

Incoming tx notification pops up after sending a transaction. screenshot:

<img width="565" alt="incoming notification" src="https://user-images.githubusercontent.com/42006886/56305925-901b7d80-6141-11e9-9354-03ad34b36e88.png">

**Comment by instagibbs** [comment]
I think it's the same issue as https://github.com/ElementsProject/elements/issues/583

makes it think it's receiving 1 unit of 000000

**Comment by instagibbs** [comment]
seems to be fixed in https://github.com/ElementsProject/elements/pull/574
