### ISSUE TITLE
QT: wrong amount and asset id for all outgoing transactions 

### ISSUE THREAD

**Issue by domegabri** [ElementsProject/elements#583]
#### version

Elements Core version v0.17.0.0-1f67fec0e (release build)

#### description

For outgoing transactions (any asset, including LBTC) amount is fixed to 1 sat and asset id to zero. screenshot: 

Overview tab:

![VirtualBox_Ubuntu 18 04_17_04_2019_19_05_05](https://user-images.githubusercontent.com/42006886/56306830-d671dc00-6143-11e9-95d4-e63bcbf3590f.png)

Transactions tab:

![VirtualBox_Ubuntu 18 04_17_04_2019_18_55_45](https://user-images.githubusercontent.com/42006886/56306624-39af3e80-6143-11e9-805e-329d76e40b3c.png)

**Comment by instagibbs** [comment]
issue confirmed, investigating

**Comment by instagibbs** [comment]
Ah! During the rebase the place where external blinded destination values/assets were recorded was moved to outside `CreateTransaction`, which conveniently means QT elides this. Easy to fix.

**Comment by instagibbs** [comment]
Resolved in https://github.com/ElementsProject/elements/pull/574
