### ISSUE TITLE
elements-qt 0.17 crash when sending an issued asset, without an LBTC balance 

### ISSUE THREAD

**Issue by domegabri** [ElementsProject/elements#585]
#### version

Elements Core version v0.17.0.0-1f67fec0e (release build)

#### description

sending an issued asset without having an LBTC balance to pay fees causes the app to crash

**Comment by instagibbs** [comment]
Can not replicate this one. I get the expected "Insufficient funds", then "Transaction creation failed!" messages.

**Comment by instagibbs** [comment]
resolved by https://github.com/ElementsProject/elements/pull/574 probably
