### ISSUE TITLE
send-to-sidechain Aborted (core dumped)

### ISSUE THREAD

**Issue by Christewart** [ElementsProject/elements#59]
Hi everyone, I'm trying to follow the [alpha-README.md](https://github.com/ElementsProject/elements/blob/alpha/alpha-README.md). I'm on step 6 trying to execute this line

>chris@chris-870Z5E-880Z5E-680Z5E:~/dev/elements$ ./contrib/sidechain-manipulation.py send-to-sidechain 2N9N5MUVcieJysWJqEUa3CXdPnGQARexHXA 1

and I am getting the following error: 

chris@chris-870Z5E-880Z5E-680Z5E:~/dev/elements$ ./contrib/sidechain-manipulation.py send-to-sidechain 2N9N5MUVcieJysWJqEUa3CXdPnGQARexHXA 1

[libsecp256k1] illegal argument: *outputlen >= ((flags & SECP256K1_FLAGS_BIT_COMPRESSION) ? 33 : 65) 

Aborted (core dumped)

==================================================
<open file '/home/chris/dev/elements/contrib/../../contracthashtool/contracthashtool -t -g -r 55210269992fb441ae56968e5b77d46a3e53b69f136444ae65a94041fc937bdb28d93321021df31471281d4478df85bfce08a10aab82601dca949a79950f8ddf7002bd915a2102174c82021492c2c6dfcbfa4187d10d38bed06afb7fdcd72c880179fddd641ea121033f96e43d72c33327b6a4631ccaa6ea07f0b106c88b9dc71c9000bb6044d5e88a210313d8748790f2a86fb524579b46ce3c68fedd58d2a738716249a9f7d5458a15c221030b632eeb079eb83648886122a04c7bf6d98ab5dfb94cf353ee3e9382a4c2fab02102fb54a7fcaa73c307cfd70f3fa66a2e4247a71858ca731396343ad30c7c4009ce57ae -d 2N9N5MUVcieJysWJqEUa3CXdPnGQARexHXA', mode 'r' at 0x7ff3cd570ed0>
==================================================
['Using testnet!', '']
Traceback (most recent call last):
  File "./contrib/sidechain-manipulation.py", line 115, in <module>
    full_contract = cht_read.split("\n")[1 + is_testnet][26:]
IndexError: list index out of range

I've supplemented `sidechains-manipulations.py` to add a few extra print statements to help debug. It now looks like this 
```python
104         elif sys.argv[1] == "send-to-sidechain":
105                 if len(sys.argv) != 4:
106                         help()
107 
108                 cht = os.popen("%s %s -g -r %s -d %s" % (contracthashtool_path, testnet_arg, redeem_script, sys.argv[2]))
109                 cht_read = cht.read()
110                 print("=" * 50)
111                 print(cht)
112                 nonce = cht_read.split("\n")[0 + is_testnet][7:]
113                 print("=" * 50)
114                 print(cht_read.split("\n"))
115                 full_contract = cht_read.split("\n")[1 + is_testnet][26:]
116                 send_address = cht_read.split("\n")[3 + is_testnet][40:]
```

Can anyone explain what I am doing wrong?

**Comment by sipa** [comment]
The libsecp256k1 API changed. You probably want to grab an older version of
it.

We'll soon release a tagged release for libsecp256k1 and switch all
software (like this) to use the stable API.

**Comment by Christewart** [comment]
Is there a specific date/commit I should be reverting to?

**Comment by droark** [comment]
I haven't tried yet (about to do so) but I compiled a binary around Aug. 1. I'll report back once I've tried. In the meantime, I think rewinding libsecp256k1 to 9d96e362a54e8d6527c510199f465600112d7117 should do the trick.

**Comment by Christewart** [comment]
This solved my issue @droark. Thank you :-)

**Comment by 0xfff** [comment]
the rewinds did not work for me, any suggestions?

**Comment by TomMcCabe** [comment]
@0xfff This rewind isn't necessary anymore. You should have the latest commit to alpha as the alpha branch has merged the new libsecp256k1 (as of https://github.com/ElementsProject/elements/commit/d4be62106b5f2f2f101de37c0bc1fa4f603cbca2). Also use @instagibbs fix (https://github.com/instagibbs/elements/commit/d390521215f1b47f8d46e8af728c5d353e1db4bf) as you'll run into another error without it.

**Comment by instagibbs** [comment]
If the last patch helps please say so on the pull request. It'll help it
get merged.
