### ISSUE TITLE
RC1 wrong directory when untarring

### ISSUE THREAD

**Issue by greenaddress** [ElementsProject/elements#592]
Steps:

Download linux tar binaries from https://github.com/ElementsProject/elements/releases/tag/elements.0.17.0-rc1

untar

expected: 

liquid-0.17.0/ (or rather liquid-0.17.0rc1 technically)

found:

elements-0.17.0/

**Comment by instagibbs** [comment]
resolved by https://github.com/ElementsProject/elements/pull/593
