### ISSUE TITLE
IsPegout not enforcing minimal push for genesis block hash

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#596]
https://github.com/ElementsProject/elements/blob/f08447909101bfbbcaf89e382f55c87b2086198a/src/script/script.cpp#L216

Should tighten this up in case someone decides to get really cute with their wallet software and funds loss occurs.

**Comment by stevenroose** [comment]
Closed as per https://github.com/ElementsProject/elements/pull/610
