### ISSUE TITLE
IsPegout should enforce that all opcodes are ≤ OP_PUSHDATA4

### ISSUE THREAD

**Issue by apoelstra** [ElementsProject/elements#598]
to match rust-elements. Related to https://github.com/ElementsProject/elements/issues/596

**Comment by roconnor-blockstream** [comment]
At this point it is probably sensible to change `data.size() == 0` to `opcode > OP_PUSHDATA4` at https://github.com/ElementsProject/elements/issues/598 and allow empty pegout_scriptPubKeys in the definition of a pegout.

This will involve reverting the change in rust-elements to reallow empty pegout_scriptPubKeys to keep everyone in sync.

**Comment by stevenroose** [comment]
Closed as per https://github.com/ElementsProject/elements/pull/610
