### ISSUE TITLE
getpeginaddress does not respect -rpcwallet when multiple wallets are open

### ISSUE THREAD

**Issue by gwillen** [ElementsProject/elements#599]
When multiple wallets are open, getpeginaddress does not specify the wallet when making a (hacky) recursive rpc call to getnewaddress.

The getnewaddress functionality should be refactored out into a helper function, or at least getpeginaddress should correctly set up the RPC request structure.

**Comment by instagibbs** [comment]
Whoops probably not the only place. I'll take a look.

**Comment by instagibbs** [comment]
same hack for `claimpegin` as well
