### ISSUE TITLE
Create new address format for confidential transactions

### ISSUE THREAD

**Issue by maaku** [ElementsProject/elements#6]
The present address format is not intended to be a standard. In particular there are probably significant improvements that can be made with respect to e.g. error correction and deterministic address size (base32/64). Also, the version byte selected was pretty much chosen at random. We should make sure it's one of the ones that has a consistent starting prefix.

**Comment by sipa** [comment]
Also: introduce payment protocol support for CT.

**Comment by voisine** [comment]
I'm thinking about how seamless integration with wallets might work. I like the idea of a bitcoin: URI with a bitcoin address, but also an argument indicating that the receiver will also accept a CT to an address that can be derived from the same bitcoin address.

This way you wouldn't need to squeeze two addresses into one QR in situations where it's impractical to exchange payment protocol request objects.

**Comment by instagibbs** [comment]
New addresses have been included in the branch `elements-0.13.1`, `CTE` being the leading characters for confidential addresses.

If ever a newer design comes along we'll likely update it again.
