### ISSUE TITLE
Finder crash opening Macos DMG

### ISSUE THREAD

**Issue by valerio-vaccaro** [ElementsProject/elements#605]
I'm experiencing some problems with macos binaries, on Macos 10.14.4 I can mounts the DMG file but Finder crash when I try to open the Volume mounted on the desktop.

The same problem was found and solved in Bitcoin https://github.com/bitcoin/bitcoin/issues/14414, I think same patch can be applied to elements scripts.

**Comment by instagibbs** [comment]
Could you cherry-pick? I can't personally test the fix anyways.

**Comment by instagibbs** [comment]
Ok made #606
