### ISSUE TITLE
combineblocksigs example test is incorrect

### ISSUE THREAD

**Issue by bitschmidty** [ElementsProject/elements#617]
Current example for combineblocksigs RPC is:

> elements-cli combineblocksigs <hex> ["signature1", "signature2", ...]

Suggested:
> elements-cli combineblocksigs <hex> '[{\"pubkey\":\"hex\",\"sig\":\"hex\"}, ...]'

**Comment by instagibbs** [comment]
resolved by https://github.com/ElementsProject/elements/pull/618
