### ISSUE TITLE
what is meaning of the transcation output?

### ISSUE THREAD

**Issue by Kingsley-Sun** [ElementsProject/elements#619]
In a transaction output in ELements , what is valuecommitment , assetcommitment , commitmentnonce mean in the fomula H = xG + v(H+rG)??

**Comment by stevenroose** [comment]
These are the Pedersen Commitments to the value and the asset and the nonce value used with them. In simple terms, they are the encrypted value and encrypted asset.

For a detailed reading on Confidential Assets, I can only refer to the [whitepaper](https://blockstream.com/bitcoin17-final41.pdf).

**Comment by Kingsley-Sun** [comment]
I do know the formula H = xG + v(H+rG) which represents a commitment in the transaction..
But when i turn to the real data in the blockchain , i got trouble...
If an output is xG + v(H+rG) in transaction... then what is valuecommitment , assetcommitment and noncecommit really mean?
For example , is assetcommitment represents (H+rG)???  or is valuecommitment represens (xG + v(H+rG)) ???

**Comment by Kingsley-Sun** [comment]
> These are the Pedersen Commitments to the value and the asset and the nonce value used with them. In simple terms, they are the encrypted value and encrypted asset.
> 
> For a detailed reading on Confidential Assets, I can only refer to the [whitepaper](https://blockstream.com/bitcoin17-final41.pdf).

I do know the formula H = xG + v(H+rG) which represents a commitment in the transaction..
But when i turn to the real data in the blockchain , i got trouble...
If an output is xG + v(H+rG) in transaction... then what is valuecommitment , assetcommitment and noncecommit really mean?
For example , is assetcommitment represents (H+rG)??? or is valuecommitment represens (xG + v(H+rG)) ???

**Comment by stevenroose** [comment]
This article might help: https://blockstream.com/2017/04/03/en-blockstream-releases-elements-confidential-assets/

IIRC, 
- the asset commitment is the value inside the brackets: `H_a + rG`
- the value commitment is the entire value: `xG + v(H_a + rG)`

(note that the two `H`'s in your formula are different H's)

The commitment nonce value is used to communicate the public key the recipient needs to recover the blinding factor (using ECDH).

**Comment by Kingsley-Sun** [comment]
> This article might help: https://blockstream.com/2017/04/03/en-blockstream-releases-elements-confidential-assets/
> 
> IIRC,
> 
> * the asset commitment is the value inside the brackets: `H_a + rG`
> * the value commitment is the entire value: `xG + v(H_a + rG)`
> 
> (note that the two `H`'s in your formula are different H's)
> 
> The commitment nonce value is used to communicate the public key the recipient needs to recover the blinding factor (using ECDH).

That's what i need!!  Thanks a lot!
By the way , when Bob wants to send  Alice some coins, is it enough for Alice only provide with an address??? ... which means that Bob just have the address of Alice , can he complete the whole transaction alone??
I had read the website many times you give before.. But its description is too simple where some details are not mentioned... Hope to be perfected as soon as possible...

**Comment by instagibbs** [comment]
The addresses have a blinding pubkey attached to them which allows the blinding to take place.

**Comment by stevenroose** [comment]
> By the way , when Bob wants to send Alice some coins, is it enough for Alice only provide with an address??? 

Elements have regular addresses and confidential addresses. In the latter, an extra blinding pubkey is provided in the address that is used to do the ECDH to get the blinding factor. So yeah "an address" is enough, but a confidential address is a normal address + pubkey. You can see how that works in the `key_io.cpp` file, or in the rust-elements code which reads easier IMO: https://github.com/ElementsProject/rust-elements/blob/master/src/address.rs#L162

**Comment by Kingsley-Sun** [comment]
> > By the way , when Bob wants to send Alice some coins, is it enough for Alice only provide with an address???
> 
> Elements have regular addresses and confidential addresses. In the latter, an extra blinding pubkey is provided in the address that is used to do the ECDH to get the blinding factor. So yeah "an address" is enough, but a confidential address is a normal address + pubkey. You can see how that works in the `key_io.cpp` file, or in the rust-elements code which reads easier IMO: https://github.com/ElementsProject/rust-elements/blob/master/src/address.rs#L162

I know the meaning of confidential address, what i wonder is how Alice get the value from the output without communicating with Bob...
For example. when Bob send Alice some coins.  the output maybe like  x*G + v*(H+r*G)... 
In this output, x*G is the pubkey from the confidetial address that you mentioned, and Alice know the x which is the private key, Alice also know the (H+r*G) which is assetcommitment in the blockchain, and also know the whole (x*G + v*(H+r*G))...
In this situation, 
1 how can Alice know the value v that she recieve???
2 is (H + r*G) gernearate by Bob?? If so , how Alice know the asset blinding factor r??

**Comment by instagibbs** [comment]
Sorry this conversation might be better on IRC if you can connect to freenode:

#sidechains-dev
