### ISSUE TITLE
issueasset

### ISSUE THREAD

**Issue by zoof-it** [ElementsProject/elements#623]
issueasset gives an error
**elementsd**
elements-cli -datadir=/home/rsk/elementswallets/vault issueasset 10 1
error: Could not connect to the server 127.0.0.1:18884
**elements-qt**
elements-cli -datadir=/home/rsk/elementswallets/vault issueasset 100 1
elements-qt: wallet/wallet.cpp:2870: bool CWallet::CreateTransaction(interfaces::Chain::Lock&, const std::vector<CRecipient>&, CTransactionRef&, std::vector<std::unique_ptr<CReserveKey> >&, CAmount&, int&, std::__cxx11::string&, const CCoinControl&, bool, BlindDetails*, const IssuanceDetails*): Assertion `g_con_elementsmode' failed.
error: Could not connect to the server 127.0.0.1:18884

Make sure the daemon server is running and that you are connecting to the correct RPC port.

Supposed to have: Creation of an asset

Can reproduce

**Versions**
bitcoind --version
Bitcoin Core Daemon version v0.18.0.0-g2472733a24a9364e4c6233ccd04166a26a68cc65
Copyright (C) 2009-2019 The Bitcoin Core developers

bitcoin-qt --version
Bitcoin Core version v0.18.0.0-g2472733a24a9364e4c6233ccd04166a26a68cc65 (64-bit)
Copyright (C) 2009-2019 The Bitcoin Core developers

elementsd --version
Elements Core Daemon version v0.17.0.1-d913803
Copyright (C) 2009-2019 The Elements Project developers
Copyright (C) 2009-2019 The Bitcoin Core developers

elements-qt --version
Elements Core version v0.17.0.1-d913803 (64-bit)
Copyright (C) 2009-2019 The Elements Project developers
Copyright (C) 2009-2019 The Bitcoin Core developers

**OS en Hardware**
ubuntu 16.04 intel i7 16GB 2TB

**Assetid bitcoin are all zeros....**
elements-cli -datadir=/home/rsk/elementswallets/vault dumpassetlabels
{
  **"bitcoin": "0000000000000000000000000000000000000000000000000000000000000000"**
}

regtest/debug.log last lines
2019-05-17T22:18:21Z New outbound peer connected: version: 70015, blocks=215, peer=0
2019-05-17T22:18:21Z New outbound peer connected: version: 70015, blocks=215, peer=1
2019-05-17T22:18:21Z New outbound peer connected: version: 70015, blocks=215, peer=2
2019-05-17T22:18:21Z New outbound peer connected: version: 70015, blocks=215, peer=3
2019-05-17T23:00:55Z [default wallet] keypool reserve 20
2019-05-17T23:00:55Z [default wallet] keypool keep 20
2019-05-17T23:00:55Z [default wallet] keypool added 1 keys (0 internal), size=2000 (1000 internal)
2019-05-17T23:00:55Z [default wallet] keypool reserve 21
2019-05-17T23:00:55Z [default wallet] keypool keep 21

**elements-cli -datadir=/home/rsk/elementswallets/vault getwalletinfo**
{
  "walletname": "",
  "walletversion": 169900,
  "balance": 5744.14978280,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 3075.00003320,
  "txcount": 211,
  "keypoololdest": 1558126507,
  "keypoolsize": 1000,
  "keypoolsize_hd_internal": 1000,
  "paytxfee": 0.00000000,
  "hdseedid": "0bbe4554b592e903b168e0d1032122ce419d18e1",
  "hdmasterkeyid": "0bbe4554b592e903b168e0d1032122ce419d18e1",
  "private_keys_enabled": true
}

**elements-cli -datadir=/home/rsk/elementswallets/vault -getinfo**
{
  "version": 170001,
  "protocolversion": 70015,
  "walletversion": 169900,
  "balance": 5744.14978280,
  "blocks": 215,
  "timeoffset": 0,
  "connections": 6,
  "proxy": "",
  "difficulty": 4.656542373906925e-10,
  "testnet": false,
  "keypoololdest": 1558126507,
  "keypoolsize": 1000,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "warnings": ""
}

**elements-cli -datadir=/home/rsk/elementswallets/vaul getnetworkinfo**
{
  "version": 170001,
  "subversion": "/Elements Core:0.17.0.1/",
  "protocolversion": 70015,
  "localservices": "000000000000040d",
  "localrelay": true,
  "timeoffset": 0,
  "networkactive": true,
  "connections": 8,
  "networks": [
    {
      "name": "ipv4",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "ipv6",
      "limited": false,
      "reachable": true,
      "proxy": "",
      "proxy_randomize_credentials": false
    },
    {
      "name": "onion",
      "limited": true,
      "reachable": false,
      "proxy": "",
      "proxy_randomize_credentials": false
    }
  ],
  "relayfee": 0.00001000,
  "incrementalfee": 0.00001000,
  "localaddresses": [
  ],
  "warnings": ""
}

**elements.conf**

regtest=1
[regtest]
rest=1

#Liability:
#assetdir=6a95ceae8e77455e9b4e5ff08e287e530c0f5a478e133d4ca952bbf562f2c367:KiloGram
#The money:
#assetdir=e71e863080384f279bbc542878a96c8c47c8962077a6ddf76d81f52bed5dd809:Zoof_It

rpcuser=xxxxxxxxxxxxxxxxxx
rpcpassword=xxxxxxxxxxxxxx
rpcport=18884

port=18886

#rpccookiefile=/home/rsk/elementswallets/vault/.cookie
rpcallowip=127.0.0.1
rpcallowip=10.57.4.208    # this is the other machine

# Over p2p we will only connect to local other elementsd
connect=localhost:18887
connect=localhost:18890
connect=localhost:18891
connect=localhost:18892

daemon=1
listen=1
txindex=1
server=1

validatepegin=0
# more info to connect to bitcoind:
#mainchainrpcport=18888
#mainchainrpcuser=uxxxx
#mainchainrpcpassword=xxxxx

mainchainrpccookiefile=/home/rsk/elementswallets/bitcoindir/.cookie

# Free money to make testing easier
initialfreecoins=2100000000000000

# Pay a transaction fee every time you send bitcoins.
# lower not possible in sidechain
#paytxfee=0.00001

**Comment by instagibbs** [comment]
Sorry this is due to "-regtest" being "Bitcoin mode". Try
"-chain=elementsregtest" instead.

**Comment by zoof-it** [comment]
Gregory,

Thank for your quick response, it works now!

Tom

Met vriendelijke groet / With kind regards,
Tom Verhagen
https://Zoof-It.com
+31-625289947
