### ISSUE TITLE
mandatory-script-verify-flag-failed (Withdraw proof validation failed - output does not match expected

### ISSUE THREAD

**Issue by Christewart** [ElementsProject/elements#63]
I'm trying to work my through the `alpha-README.md` file. I'm on this step: 

``` bash
chris@chris-870Z5E-880Z5E-680Z5E:~/dev/elements$ ./contrib/sidechain-manipulation.py claim-on-sidechain 2NFRtY9CUwWCjBS6xbhJUkNYgs5HKzLoyyd 7d3e344f3b7ba903f608e29e9046c981 89cad7aff265ea0883a629f8106aa9bfe70646336bb9e7543a7a4640476bd3bd
```

and I'm getting the following error: 

``` bash
Redeeming from utxo eb37c77d94e284b52b58eeec52b43591bf0cebe61da1c29ecaf0347b12d5bcab:0 (value 0.01, refund 0.0095)
Traceback (most recent call last):
  File "./contrib/sidechain-manipulation.py", line 237, in <module>
    txid = sidechain.sendrawtransaction(res_tx)
  File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 138, in __call__
    raise JSONRPCException(response['error'])
JSONRPCException: -26: 16: mandatory-script-verify-flag-failed (Withdraw proof validation failed - output does not match expected)

Got the following error from an RPC Call:
{u'message': u'16: mandatory-script-verify-flag-failed (Withdraw proof validation failed - output does not match expected)', u'code': -26}
```

My first guess was that my bitcoind instance wasn't synced up to the network, but at the time of this post I ran

``` bash
chris@chris-870Z5E-880Z5E-680Z5E:~/dev/elements$ bitcoin-cli -testnet getblockcount
606934
```

So I'm not really sure what could be wrong.

**Comment by apoelstra** [comment]
Hi @Christewart, sorry for the delay in investigating this. This is a bug in `sidechain-manipulation.py`.

It's an alpha consensus rule that any sidechain claim transactions have a locked sidechain output as input, then your address as output, follow immediately by a change output whose **scriptPubKey is identical to the scriptPubKey of the original locked output**. That is, you are "putting the change back where it came from".

In `sidechain-manipulation.py:231` the change output is hardcoded to be the same as the alpha genesis output (which describes 21m coins with no corresponding locked Testnet output). However, the genesis output is not the only locked sidechain output; there are other outputs which correspond to coins users have locked when withdrawing from Alpha to Testnet.

So the bug you're seeing is that `sidechain-manipulation.py` is trying to unlock some locked output created by some user (so it does not originate from the genesis output), then send the coins (a) to you, and (b) "back" to the genesis output.

So the script needs to be fixed to look at which output it's spending, and to use that.

cc @TheBlueMatt can I just have `UTXOFinder` store its scriptpubkey then assign that to `relock_scriptPubKey` on line 231?

**Comment by guillv** [comment]
Hi,
I have the same problem even after fixing the script.
Is there another solution ?

**Comment by Sarodh** [comment]
I'm getting the same problem, How is the secondScriptPubKeyhash exactly calculated? 

`"asm" : "OP_IF 11908 24f8196cb480b307d56bc414e9f7c9c8f4e30ed594a7dc3558bb4543037e9754 1 0 9eac001049d5c38ece8996485418421f4a01e2d7 983542176c5e173c003bb629eb58e3f4e14df8665e3e191ab531f10f56050000 OP_REORGPROOFVERIFY OP_ELSE 144 OP_NOP3 OP_DROP OP_HASH160 512102a065bf5aa16b59346c8f08dfffd95fbd64 OP_REORGPROOFVERIFY OP_MIN OP_UNKNOWN OP_UNKNOWN OP_SWAP OP_RESERVED2 OP_ROT OP_UNKNOWN OP_UNKNOWN OP_CAT OP_NUMEQUALVERIFY OP_XOR [error]"`

**Comment by TomMcCabe** [comment]
@Sarodh The `secondScriptPubKeyHash` is just the hash of the `secondScriptPubKey`.

secondScriptPubKey: `OP_DROP 144 OP_LESSTHANOREQUAL`

In hex: `75029000a1`

Sha256(Ripemd160(secondScriptPubKey)) == `9eac001049d5c38ece8996485418421f4a01e2d7`

**Comment by Sarodh** [comment]
Thanks @TomMcCabe

**Comment by instagibbs** [comment]
peg-in system was overhauled
