### ISSUE TITLE
Makefile: elements-tx target doesn't work

### ISSUE THREAD

**Issue by jtimon** [ElementsProject/elements#641]
It seems like the target...
```
make elements-tx
```

...doesn't work. It can still be build with make all, but not individually.

Last reproduced in commit 551483eae50ff2ee48ed17d6b22bb1a26284b635

**Comment by stevenroose** [comment]
Can you try again on master? It works for Greg and me.

**Comment by instagibbs** [comment]
it just started working for me(???)

**Comment by stevenroose** [comment]
That's in `src/` right? `make src/elements-tx` works here, `elements-wallet` also.

**Comment by jtimon** [comment]
Yeah, it seems fixed on 89dd20a18642f472e4f255bbfd0cf1d49deb58d3 , thanks.
Closing.
