### ISSUE TITLE
After upgradewallet, fundrawtransaction uses non change address as change

### ISSUE THREAD

**Issue by LeoComandini** [ElementsProject/elements#659]
Wallet created with 0.14, later with 0.17 upgraded with upgradewallet.

`fundrawtransction` uses non change addresses for the change.
The very next `getnewaddress` call returns the same address used as change.

    $ DUMMY=VJL5bwudesLgrLxF4SPVyxvoWrDJhBpKf9YxQgVpMzfuLDSGndbWS832vZmKoV5KhrC2RC4SKzvn2ZbE
    $ TXC=$(liquid-cli createrawtransaction "[]" "{\"$DUMMY\":0.0001234}")
    $ TXF=$(liquid-cli fundrawtransaction $TXC | jq -r .hex)
    $ ADDR=$(liquid-cli getnewaddress)
    $ liquid-cli getaddressinfo $ADDR
    {
      "address": "VJL8rZ3UwNfEkRACELoAwxYAayY7WowZ7wKNkrD59j9E9EmzPaqv7S9PT7T8h2YDS6Z5jPhxTzmLgdAV",
      "scriptPubKey": "a9144bf2661eff22f1ca558549da01b2d077cc3bc9de87",
      "ismine": true,
      "iswatchonly": false,
      "isscript": true,
      "iswitness": false,
      "script": "witness_v0_keyhash",
      "hex": "00141c2f767cd5ba1d5aa51067e0d6a2ef7589ad0ef3",
      "pubkey": "03e6008971b88faf6cc8078fadb16ed913a6d3c8c7bd67c7966368c019eaba8f91",
      "embedded": {
        "isscript": false,
        "iswitness": true,
        "witness_version": 0,
        "witness_program": "1c2f767cd5ba1d5aa51067e0d6a2ef7589ad0ef3",
        "pubkey": "03e6008971b88faf6cc8078fadb16ed913a6d3c8c7bd67c7966368c019eaba8f91",
        "address": "ex1qrshhvlx4hgw44fgsvlsddgh0wky66rhn9hr480",
        "scriptPubKey": "00141c2f767cd5ba1d5aa51067e0d6a2ef7589ad0ef3"
      },
      "confidential": "VJL8rZ3UwNfEkRACELoAwxYAayY7WowZ7wKNkrD59j9E9EmzPaqv7S9PT7T8h2YDS6Z5jPhxTzmLgdAV",
      "confidential_key": "027a157aa311ff7c70f745652538dcb258cb105ce3ea262baba988fe5348f21742",
      "unconfidential": "Gp76To3Bt3W2ZRhyxVsgGAh3yGkmRgmQuU",
      "label": "",
      "timestamp": 1554228459,
      "hdkeypath": "m/0'/0'/51'",
      "hdseedid": "822d37757b7e1d372c1b425c25f3f06b9066d923",
      "hdmasterkeyid": "822d37757b7e1d372c1b425c25f3f06b9066d923",
      "labels": [
        {
          "name": "",
          "purpose": "receive"
        }
      ]
    }

    $ liquid-cli decoderawtransaction $TXF
    {
      "txid": "02307ff3b287e583c12b7893d33d784afd7b79c8386a890a7ab2cb32ccc64bf6",
      "hash": "02307ff3b287e583c12b7893d33d784afd7b79c8386a890a7ab2cb32ccc64bf6",
      "wtxid": "02307ff3b287e583c12b7893d33d784afd7b79c8386a890a7ab2cb32ccc64bf6",
      "withash": "ab3393f4fb64685a4de07ac89c6903d6a0ba107c87fff33c9a981a7590bae48e",
      "version": 2,
      "size": 294,
      "vsize": 294,
      "weight": 1176,
      "locktime": 0,
      "vin": [
        {
          "txid": "a9b709f3f936d5dc984fbf85fc1f471588f8a3947b0e51fe62eb184324aa08f9",
          "vout": 1,
          "scriptSig": {
            "asm": "",
            "hex": ""
          },
          "is_pegin": false,
          "sequence": 4294967293
        }
      ],
      "vout": [
        {
          "value": 0.00012340,
          "asset": "6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d",
          "commitmentnonce": "020202020202020202020202020202020202020202020202020202020202020202",
          "commitmentnonce_fully_valid": true,
          "n": 0,
          "scriptPubKey": {
            "asm": "OP_HASH160 0000000000000000000000000000000000000000 OP_EQUAL",
            "hex": "a914000000000000000000000000000000000000000087",
            "reqSigs": 1,
            "type": "scripthash",
            "addresses": [
              "GhBXQEdEh35AtuSNxMzRutcgYg3nkvq5Wb"
            ]
          }
        },
        {
          "value": 0.00075728,
          "asset": "6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d",
          "commitmentnonce": "027a157aa311ff7c70f745652538dcb258cb105ce3ea262baba988fe5348f21742",
          "commitmentnonce_fully_valid": true,
          "n": 1,
          "scriptPubKey": {
            "asm": "OP_HASH160 4bf2661eff22f1ca558549da01b2d077cc3bc9de OP_EQUAL",
            "hex": "a9144bf2661eff22f1ca558549da01b2d077cc3bc9de87",
            "reqSigs": 1,
            "type": "scripthash",
            "addresses": [
              "Gp76To3Bt3W2ZRhyxVsgGAh3yGkmRgmQuU"
            ]
          }
        },
        {
          "value": 0.00001932,
          "asset": "6f0279e9ed041c3d710a9f57d0c02928416460c4b722ae3457a11eec381c526d",
          "commitmentnonce": "",
          "commitmentnonce_fully_valid": false,
          "n": 2,
          "scriptPubKey": {
            "asm": "",
            "hex": "",
            "type": "fee"
          }
        }
      ]
    }

**Comment by instagibbs** [comment]
Ok I've confirmed the issue. Seems like it's drawing external chain keys from external pool, and adding them to the internal keypool once used? I'll figure it out.

**Comment by LeoComandini** [comment]
I investigated a bit and the problem seems to be that fundrawtransaction does not remove the change keys from the keypool. This https://github.com/ElementsProject/elements/commit/cf82a9e704f56d245cf512d76ba9d0e6b178f3b0 addressed, but it has been removed later. This problem occurs also for non upgraded wallets.

**Comment by instagibbs** [comment]
That's only a partial issue. Upgrading wallets should get rid of the old keypool as well.

**Comment by instagibbs** [comment]
The biggest issue here is that it's not drawing from the internal keypool at all.

**Comment by instagibbs** [comment]
I'm replicating this on Core master, fwiw.

1) Create wallet using 0.14.3
2) Stop
3) Load wallet using master with `-upgradewallet`
4)
```
getwalletinfo
{
  "walletname": "test.dat",
  "walletversion": 169900,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
  "keypoololdest": 1560344352,
  "keypoolsize": 2000,
  "keypoolsize_hd_internal": 0,
  "paytxfee": 0.00000000,
  "hdseedid": "a9e2788e2871531d9b54b1fc85ff822dffcc2707",
  "private_keys_enabled": true,
  "scanning": false
}

getrawchangeaddress
2N1ZX1ZLgRABqcec4XDVMJmMFRNqnJZBfpA

getwalletinfo
{
  "walletname": "test.dat",
  "walletversion": 169900,
  "balance": 0.00000000,
  "unconfirmed_balance": 0.00000000,
  "immature_balance": 0.00000000,
  "txcount": 0,
  "keypoololdest": 1560344352,
  "keypoolsize": 1999,
  "keypoolsize_hd_internal": 1,
  "paytxfee": 0.00000000,
  "hdseedid": "a9e2788e2871531d9b54b1fc85ff822dffcc2707",
  "private_keys_enabled": true,
  "scanning": false
}

getaddressinfo 2N1ZX1ZLgRABqcec4XDVMJmMFRNqnJZBfpA
{
  "address": "2N1ZX1ZLgRABqcec4XDVMJmMFRNqnJZBfpA",
  "scriptPubKey": "a9145b36b3eb5ae046fcaae77a25d6cd93155f33c9ba87",
  "ismine": true,
  "solvable": true,
  "desc": "sh(wpkh([510ad933/0'/0'/1']022a1576b06ca44fbfd3956afe0b5a4933fbeda8a66c308de8074b7b186fa5b4b8))#936fhdgy",
  "iswatchonly": false,
  "isscript": true,
  "iswitness": false,
  "script": "witness_v0_keyhash",
  "hex": "001458aed9491c976d7bce0d0323ff8d1bc139a338bb",
  "pubkey": "022a1576b06ca44fbfd3956afe0b5a4933fbeda8a66c308de8074b7b186fa5b4b8",
  "embedded": {
    "isscript": false,
    "iswitness": true,
    "witness_version": 0,
    "witness_program": "58aed9491c976d7bce0d0323ff8d1bc139a338bb",
    "pubkey": "022a1576b06ca44fbfd3956afe0b5a4933fbeda8a66c308de8074b7b186fa5b4b8",
    "address": "bcrt1qtzhdjjgujakhhnsdqv3llrgmcyu6xw9mvwxxwh",
    "scriptPubKey": "001458aed9491c976d7bce0d0323ff8d1bc139a338bb"
  },
  "ischange": true,
  "timestamp": 1560344273,
  "hdkeypath": "m/0'/0'/1'",
  "hdseedid": "a9e2788e2871531d9b54b1fc85ff822dffcc2707",
  "hdmasterfingerprint": "510ad933",
  "labels": [
  ]
}
```

**Comment by instagibbs** [comment]
https://github.com/bitcoin/bitcoin/issues/16193 Filed an issue upstream, as I seem to be able to replicate the exact behavior.

**Comment by instagibbs** [comment]
Eh it turns out the issue is "expected behavior", but there are 0 tests for it.

Investigating the other half of your issue to see if it's related.

**Comment by instagibbs** [comment]
Turns out other half is our fault. Fix included: https://github.com/ElementsProject/elements/pull/660

**Comment by stevenroose** [comment]
Just to be clear, the actual reuse only happens after a wallet is migrated from 0.14.* to 0.17.* and upgraded, right?

**Comment by instagibbs** [comment]
No, due to internal API changes we broke the CReserveKey lifecycle.
