### ISSUE TITLE
RPC signblock should fail if the block can not be signed

### ISSUE THREAD

**Issue by jonasnick** [ElementsProject/elements#66]
Currently if the daemon has no key to sign the block calling the "signblock" RPC returns an empty "" signature. Instead we want to throw an RPC error in that case. [GenerateProof](https://github.com/ElementsProject/elements/blob/71800421044ff88e12156f1a5bbab369bb659a71/src/rpcmining.cpp#L305) returns a bool, but this indicates that a full proof has been created and can be successfully verified, and not that a partial proof (signature) has been created.

**Comment by instagibbs** [comment]
The format has changed dramatically, with an array with any generated signatures attached as an object.
