### ISSUE TITLE
class BitcoinGUI error

### ISSUE THREAD

**Issue by amirelayyan** [ElementsProject/elements#681]
Hello,

I'm having an issue when executing the **make** command into the terminal. Attempting to install elements on Debian 9.

![Screenshot from 2019-07-23 09-56-42](https://user-images.githubusercontent.com/25713808/61698758-8c475a80-ad31-11e9-8c9d-72973892a7ea.png)

Any help would be greatly appreciated,
Thanks in advance

**Comment by instagibbs** [comment]
I suspect a make clean may help?

**Comment by amirelayyan** [comment]
That solved the issue. Thank you

**Comment by instagibbs** [comment]
cheers!
