### ISSUE TITLE
Elements-Qt 0.17.0 macOS release crashes when double clicking on a tx

### ISSUE THREAD

**Issue by grubles** [ElementsProject/elements#682]
**Describe the issue**
When double clicking on a transaction in the GUI in order to see details about the transaction, -Qt crashes. 

**What behavior did you expect?**
A separate window should pop up with the details of the transaction

**What was the actual behavior (provide screenshots if the issue is GUI-related)?**
-Qt crashes. 

**How reliably can you reproduce the issue, what are the steps to do so?**
Very reliably. Although this only occurs with a specific transaction in my case. Other transactions do not crash the application. 

Steps to reproduce are:
* Open up Elements-Qt
* Double click on the transaction
* -Qt will then crash

**What version of Bitcoin Core are you using, where did you get it (website, self-compiled, etc)?**
None. Using `validatepegin=0` in this case.

**What type of machine are you observing the error on (OS/CPU and disk type)?**
MacBook Pro 14,1
Intel Core i5
Apple NVMe SSD

**Any extra information that might be useful in the debugging process.**
The transaction that crashes -Qt is an atomic asset swap between an asset I own and an asset a friend owns (ie. not in my wallet).  

Other transactions work fine and do not crash the application. 

**This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.**
The macOS-generated crash report is attached.
[elementsqt_crashreport.txt](https://github.com/ElementsProject/elements/files/3427083/elementsqt_crashreport.txt)

**Comment by instagibbs** [comment]
> The transaction that crashes -Qt is an atomic swap. Other transactions work fine and do not crash the application.

Can you explain the structure of the transaction? What kind of swap? Which parts the wallet is watching/considers its own? etc

**Comment by instagibbs** [comment]
Ok this error has been fixed in 0.17.0.1, please try the RCs: https://github.com/ElementsProject/elements/releases/tag/elements-0.17.0.1_rc2
