### ISSUE TITLE
elements-qt grows too large for screen once you have many assets

### ISSUE THREAD

**Issue by allenpiscitello** [ElementsProject/elements#685]
I have dozens of assets in my wallet, and now the window grows too large that it cannot stay on my screen and I cannot do anything that would normally be at the bottom of the window.

To solve this, we should have a scroll on the asset list on the overview.

**Comment by instagibbs** [comment]
this would be done in `src/qt/forms/overviewpage.ui`, I really have 0 experience on writing this GUI stuff in such a raw form. Maybe QT creator is a thing to try.
