### ISSUE TITLE
Make Install error // Elements Tutorial

### ISSUE THREAD

**Issue by walter-grace** [ElementsProject/elements#687]
I am using Ubuntu and I am having trouble with the **make install** feature, I am getting this error:
I followed everything in the [https://elementsproject.org/elements-code-tutorial/installing-elements](url) 

_make install
Making install in src
make[1]: Entering directory '/home/walt/elements/src'
make[2]: Entering directory '/home/walt/elements/src'
make[3]: Entering directory '/home/walt/elements'
make[3]: Leaving directory '/home/walt/elements'
make[3]: Entering directory '/home/walt/elements/src'
make[4]: Entering directory '/home/walt/elements'
make[4]: Leaving directory '/home/walt/elements'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool --preserve-dup-deps  --mode=install /usr/bin/install -c   libelementsconsensus.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libelementsconsensus.so.0.0.0 /usr/local/lib/libelementsconsensus.so.0.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libelementsconsensus.so.0.0.0': Permission denied
Makefile:4979: recipe for target 'install-libLTLIBRARIES' failed
make[3]: *** [install-libLTLIBRARIES] Error 1
make[3]: Leaving directory '/home/walt/elements/src'
Makefile:13324: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/walt/elements/src'
Makefile:12996: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/walt/elements/src'
Makefile:783: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
_

**Comment by instagibbs** [comment]
Try 'make clean' and rebuild first

**Comment by walter-grace** [comment]
now getting this error when running 'make install', it looked like the 'make clean' and rebuildd was working. Not sure if this is the same error as above

_sts.o
  GEN  	qt/test/moc_apptests.cpp
  CXX  	qt/test/qt_test_test_elements_qt-moc_apptests.o
  GEN  	qt/test/moc_compattests.cpp
  CXX  	qt/test/qt_test_test_elements_qt-moc_compattests.o
  GEN  	qt/test/moc_rpcnestedtests.cpp
  CXX  	qt/test/qt_test_test_elements_qt-moc_rpcnestedtests.o
  GEN  	qt/test/moc_uritests.cpp
  CXX  	qt/test/qt_test_test_elements_qt-moc_uritests.o
  GEN  	qt/test/moc_addressbooktests.cpp
  CXX  	qt/test/qt_test_test_elements_qt-moc_addressbooktests.o
  GEN  	qt/test/moc_wallettests.cpp
  CXX  	qt/test/qt_test_test_elements_qt-moc_wallettests.o
  GEN  	qt/test/moc_paymentservertests.cpp
  CXX  	qt/test/qt_test_test_elements_qt-moc_paymentservertests.o
  CXXLD	qt/test/test_elements-qt
make[3]: Entering directory '/home/walt/elements/src'
make[4]: Entering directory '/home/walt/elements'
make[4]: Leaving directory '/home/walt/elements'
 /bin/mkdir -p '/usr/local/lib'
 /bin/bash ../libtool --preserve-dup-deps  --mode=install /usr/bin/install -c   libelementsconsensus.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libelementsconsensus.so.0.0.0 /usr/local/lib/libelementsconsensus.so.0.0.0
/usr/bin/install: cannot create regular file '/usr/local/lib/libelementsconsensus.so.0.0.0': Permission denied
Makefile:4979: recipe for target 'install-libLTLIBRARIES' failed
make[3]: *** [install-libLTLIBRARIES] Error 1
make[3]: Leaving directory '/home/walt/elements/src'
Makefile:13324: recipe for target 'install-am' failed
make[2]: *** [install-am] Error 2
make[2]: Leaving directory '/home/walt/elements/src'
Makefile:12996: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/walt/elements/src'
Makefile:783: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1
walt@walt-VirtualBox:~/elements$_

**Comment by stevenroose** [comment]
To be honest, I never `make install`'ed Elements.. Does it do anything else than `make all` and `cp ./src/elementsd ./src/elements-cli ./src/elements-tx ./src/qt/elements-qt /usr/bin/`?

**Comment by walter-grace** [comment]
> To be honest, I never `make install`'ed Elements.. Does it do anything else than `make all` and `cp ./src/elementsd ./src/elements-cli ./src/elements-tx ./src/qt/elements-qt /usr/bin/`?

Will try, I have /usr/local/bin/elementsd ; cheers
