### ISSUE TITLE
Scanning key is reused

### ISSUE THREAD

**Issue by greenaddress** [ElementsProject/elements#69]
Confidential transaction addresses reuse the scanning key, https://github.com/ElementsProject/elements/blob/alpha/src/rpcwallet.cpp#L107

This is bad for privacy and alpha should use a new key per transaction

IRC conversation on #sidechains-dev for context:

GAit 
14:58 https://github.com/ElementsProject/elements/blob/alpha/src/rpcwallet.cpp#L107 - in which circumstances is it safe to reuse the scanning key? what implications does it have in terms of usecases and privacy? should it be changed per tx if possible?
maaku
16:31 scanning keys are analagous to public derivaiton of HD wallets — there are situations where you might want to delegate the ability to see an entire series of payemtns
16:31 that is an important feature to support
16:32 but in general, and especially with the bitcoin-qt bag-of-keys wallet model, per-tx scanning keys provide better privacy
16:32 alphad presently supports only one per-wallet scanning key, and this is considered a bug
GAit
16:42 thanks maaku, very useful
16:43 makes sense. In an HD contest one would use a separate derivation branch and generate a scanning key per tx, privately derived/hardened.

**Comment by instagibbs** [comment]
Fixed in 683dd3cdbebd1814ddfb61b2990e0c47d15fcc4d using a blinding derivation key hmac'd with the scriptpubkey
