### ISSUE TITLE
Mac Installer alignment is off

### ISSUE THREAD

**Issue by allenpiscitello** [ElementsProject/elements#724]
<img width="499" alt="Screen Shot 2019-09-27 at 3 17 31 PM" src="https://user-images.githubusercontent.com/7843777/65796336-f3b6c780-e131-11e9-8540-2768b85eb7f3.png">
<img width="499" alt="Screen Shot 2019-09-27 at 3 00 40 PM" src="https://user-images.githubusercontent.com/7843777/65796337-f44f5e00-e131-11e9-8137-d4322c94c75b.png">

**Comment by instagibbs** [comment]
Issue is likey here https://github.com/ElementsProject/elements/blob/master/contrib/macdeploy/custom_dsstore.py

Bitcoin-Qt.app doesn't exist
