### ISSUE TITLE
Implement cost function

### ISSUE THREAD

**Issue by jonasnick** [ElementsProject/elements#73]
Cost functions estimate resource requirements during block validation. A new consensus rule would be introduced such that blocks above a certain cost limit are invalid. The cost function (and cost limit) should be a chain specific parameter to allow accounting for chain specific features. In Bitcoin, for example, the node costs are mostly driven by signature hashing. 

This [branch](https://github.com/instagibbs/bitcoin/commits/rt) is an example of a resource tracker for bitcoin.

**Comment by instagibbs** [comment]
Let's just get simplicity working and ban everything else.
