### ISSUE TITLE
Use with NBitcoin to add to BTCPay Server

### ISSUE THREAD

**Issue by nharmon9** [ElementsProject/elements#731]
Both of the available Liquid Versions on NBitcoin.Altcoin spit out different errors.

v3_14_1_23: 'Hash of downloaded file does not match...'

v3_14_1_21: 'This platform does not support tests involving this crypto currency, DownloadData for this OS are unavailable'

macOS 10.14.6

Visual Studio Code

**Comment by instagibbs** [comment]
This is a question for NBitcoin?
