### ISSUE TITLE
0.19 sync up checklist

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#743]
Running list before I forget:

[ ] - Core 0.19.0 release
[ ] - merge to the 0.19 branch off point of Core master
[ ] - fix tests: update bitcoin compatibility tests, fix functional/unit tests, make sure travis jobs match Core builds + extra ones, make sure all travis output looks correct
[ ] - make sure assets tutorial still works
[ ] - validate master tip: tests pass, manual re-sync of liquidv1 network
[ ] - branch off elements-0.19
[ ] - sync with Core 0.19 branch up to release commit
[ ] - Make RC
[ ] - elements-0.19 release!

**Comment by RdeWilde** [comment]
How does this work? Is this manual comparison?

**Comment by stevenroose** [comment]
No this is kind of the checklist we used for the 0.18 sync up. We do all the steps when we want to sync up with an upstream release. We're definitely overdue syncing with 0.19.

**Comment by apoelstra** [comment]
Closing, as we have a different merge/branch strategy for releases now.
