### ISSUE TITLE
Q) How to change signblockscript

### ISSUE THREAD

**Issue by nayuta-ueno** [ElementsProject/elements#762]
I'd like to change `signblockscript` after generating chain(dynamic federation?).
Can I change block sign script while keeping current chain data?

**Comment by instagibbs** [comment]
In lieu of real user docs, here's demonstration of how to transition using python interface: https://github.com/ElementsProject/elements/blob/master/test/functional/feature_dynafed.py#L235

Does this help?

**Comment by instagibbs** [comment]
Apologies for no real external documents, we're working on it...

**Comment by nayuta-ueno** [comment]
> In lieu of real user docs, here's demonstration of how to transition using python interface: 
> https://github.com/ElementsProject/elements/blob/master/test/functional/feature_dynafed.py#L235

Thank you!
I'll read this script.
