### ISSUE TITLE
QR code Liquid address does not fit in window.

### ISSUE THREAD

**Issue by nwoodfine** [ElementsProject/elements#763]
Cosmetic issue—the Liquid addresses are too long for the QR code display, and get cut off at the edges. See attached image.
![image](https://user-images.githubusercontent.com/17946939/67948291-02ecd180-fc18-11e9-8af4-fafd5dcc7e4f.png)

**Comment by instagibbs** [comment]
which OS/version? Ubuntu for me is ok.

**Comment by nwoodfine** [comment]
Sorry should have said: MacOS. Tested on two separate devices.

**Comment by allenpiscitello** [comment]
I see the same thing on Ubuntu. It might depend on the address format? blech32 is fine, but standard not.

**Comment by instagibbs** [comment]
oh, base58 addresses, right. Can confirm.

**Comment by instagibbs** [comment]
made a fix at #785
