### ISSUE TITLE
How can I generate an address in another language, is there a related document?

### ISSUE THREAD

**Issue by debuggor** [ElementsProject/elements#764]
like"Q664QL2GmokdHS9Kd6c6isbVKbbhkMaPfo"
how can i generate it by java,is there a related document?
thanks

**Comment by instagibbs** [comment]
It's a base58 address with a different prefix value. Should be able to decode it, and modify as required.

**Comment by debuggor** [comment]
@instagibbs Can I generate it like the address of the BTC? Just need to change the address prefix? Is it the same as BTC's address generation rules?
thanks

**Comment by instagibbs** [comment]
yes, at least for unconfidential addresses

**Comment by debuggor** [comment]
@instagibbs For unconfidential transactions, is the same as signing and multi-signing?

**Comment by instagibbs** [comment]
signature hash is different, but underlying bitcoin script for signatures is identical
