### ISSUE TITLE
Blockchain size display error and hidden text (MacOS)

### ISSUE THREAD

**Issue by nwoodfine** [ElementsProject/elements#765]
MacOS app requesting a few gazillion GB of data for the Liquid ("bitcoin") block chain on first time startup (MacOS binary). Further down shows `%n GB`.

Also appears to be some text hidden in the middle by some dodgy window formatting.

 ![image](https://user-images.githubusercontent.com/17946939/68105555-712fdd80-ff11-11e9-9e2f-16583b27f273.png)

**Comment by instagibbs** [comment]
Ok this is the magic of uninitialized variables in chainparams. Someone should look up what the actual size is for liquidv1 and initialize those args.
