### ISSUE TITLE
change block header after 431 blocks automatically?

### ISSUE THREAD

**Issue by nayuta-ueno** [ElementsProject/elements#767]
elements commit b33439294612a23eb0798239c8b67392de4d78ae

I tried to generate a lot of blocks: [Block creation in a Strong Federation - Block Signing](https://elementsproject.org/elements-code-tutorial/block-creation).
After generating 431 blocks, `signblock` return "Signing dynamic blocks requires the witnessScript argument"(success sign by adding `$REDEEMSCRIPT`).

Do Elements change block header after 431 blocks automatically?
I'd like to use `electrs`, but rust-elements returns error after 432 blocks.
> Caused by: parse failed: data not consumed entirely when explicitly deserializing

**Comment by stevenroose** [comment]
I assume you are creating `elementsregtest` blocks? Do you fill a value for the `-con_dyna_deploy_start` variable? 431 or 432 seems like a quite arbitrary number. Are you providing `-dynamic_epoch_length`?

**Comment by nayuta-ueno** [comment]
> I assume you are creating elementsregtest blocks?

Yes. I'm running the tutorial.
https://github.com/ElementsProject/elements/blob/master/contrib/assets_tutorial/elements1.conf

> Do you fill a value for the -con_dyna_deploy_start variable?

like below parameter:
```
-signblockscript=5221020.......1f88352ae -con_max_block_sig_size=150 -con_dyna_deploy_start=0
```

> Are you providing -dynamic_epoch_length?

No. only `signblockscript`, `con_max_block_sig_size`, `con_dyna_deploy_start`.

**Comment by nayuta-ueno** [comment]
blockheader 431

```
$ e1-cli getblockheader accd1b53ace8a6ec901b51dc660858cb4b5afd6ec4afc9ec78a6d0e1133d4d0f false
00000032e86e27bcdf78a8a4385b901fe5f28a3107c5c4c35fdcc2179f5f7f930fc297240f7ad761c860facf806e7a7f9e62b57ec2e540fd388ed48afd62fb186a83cb675458c15daf010000475221020aa543cd37bdda8a08d42c50257d609b2c2012c9e03fc7866e01345ac2eb4bf62103e765f2d6e41034087894a5c0d39021bc6e40db427da23321bc88b2f62d31f88352ae8f00463044022034b6d01138d553846104aed80957564c3c446a6c18bc641a3aa2a2003018e52602201c9d249b2fb448fb105d87a0a0469e37392b132d8259ad25de6a83cbe087e4e346304402200528442ccd221bbbc44ffa003c279a1d97160469e9f3306c98b0523575c45cab022020ccbb6ceb40f04fe4f638371a04057d63cae3716a101df39e25c6eeff056f1c
```

blockheader 432
```
$ e1-cli getblockheader 73abdd73bc9166711b5c22c799fc8c4ccdbb9bbb43c633e39ae01a2b7ee008b4 false
000000a00f4d3d13e1d0a678ecc9afc46efd5a4bcb580866dc511b90eca6e8ac531bcdac80be00c422c421b04755fdd2b466b6defd527cb8e46980c2f6245b18688493e85458c15db0010000012200206c4e59c851d3ee13c5edadedf3d015e95dbd808a7949ce175e551824e36f5c4cdd00000000040047304402204f51da67a543857b0e4c2fd7a3ec9b4fdff1763fbdd6256868a32c7231242ce702203117d7812f8a7f17b492ee88fbc400b227cb4f9e93ea04c99ed92371dadc112c01473044022011edd17b4cd18abb8827450fd71fa49e6e63b055f6be2eeeaebbb16cb6c214f5022016459e0a817bd311bb23d1772d7e4dfeae6ad0c02e60b0e501850b93aa738b9b01475221020aa543cd37bdda8a08d42c50257d609b2c2012c9e03fc7866e01345ac2eb4bf62103e765f2d6e41034087894a5c0d39021bc6e40db427da23321bc88b2f62d31f88352ae
```

**Comment by instagibbs** [comment]
You have likely activated dynamic federations. If you want to disable it you should set `con_dyna_deploy_start` to 0 or some very high number

**Comment by nayuta-ueno** [comment]
I try `-con_dyna_deploy_start=0` and `-con_dyna_deploy_start=99999`, but same behavior.

**Comment by nayuta-ueno** [comment]
`con_dyna_deploy_start` maybe copy to `nTimeStart`.

https://github.com/ElementsProject/elements/blob/08023b0b4ee30843b66f2d62dfc7f8eb7906fbcb/src/versionbits.cpp#L56

Is it necessary to check `nTimeStart > 0`(or `nTimeStart==0` start of function) ?

**Comment by instagibbs** [comment]
That is upstream code which has received lots of review. I don't expect
there's a bug there.

**Comment by nayuta-ueno** [comment]
> That is upstream code which has received lots of review.

OK, maybe `con_dyna_deploy_start=0` don't mean disable feature.
I try `con_dyna_deploy_start=5000000000` and it looks good.
Thank you!

**Comment by instagibbs** [comment]
Note that `con_dyna_deploy_start` is a timestamp start, not a block height(as per BIP9). So `99999` is not high enough. 

in the functional tests I did:
`f.write("con_dyna_deploy_start="+str(2**31)+"\n")` to make sure it never activates.

you're right `0` just means the signaling window starts at time 0... not disabled.

sorry!

**Comment by instagibbs** [comment]
Anytime there's confusion about these features a good place to start looking is the functional tests; I forget too :)
