### ISSUE TITLE
IndexError: list index out of range (sidechain-manipulation.py line 141)

### ISSUE THREAD

**Issue by Geremia** [ElementsProject/elements#79]
Running this:
`$ ./contrib/sidechain-manipulation.py send-to-sidechain 2NGN94dzNQ764Ef2aMyj5G87mzCGio4i2jh 1`

Produces this error on line 141 of `sidechain-manipulation.py`:
```
[libsecp256k1] illegal argument: *outputlen >= ((flags & SECP256K1_FLAGS_BIT_COMPRESSION) ? 33 : 65)
Traceback (most recent call last):
  File "./contrib/sidechain-manipulation.py", line 141, in <module>
    full_contract = cht_read.split("\n")[1 + is_testnet][26:]
IndexError: list index out of range
```

I'm using the latest commits of everything, as of the date of posting this issue.

**Comment by Geremia** [comment]
[This patch to `contracthashtool`](https://github.com/Blockstream/contracthashtool/pull/8/files?diff=split) fixed this issue.

**Comment by instagibbs** [comment]
Great thanks for reporting back.

**Comment by sipa** [comment]
Fixed.
