### ISSUE TITLE
Asset Tutorial: elements2.conf Doesn't have regtest mode

### ISSUE THREAD

**Issue by codeShark149** [ElementsProject/elements#801]
`elements2.conf` file provided in `elements/contrib/asset_tutorial` Doesn't specifies 
`chain=elementsregtest` 

As a result `e2-cli` (https://elementsproject.org/elements-code-tutorial/working-environment) attempts to connect to wrong port. 

Or am I missing something?

**Comment by philippem** [comment]
hi @codeShark149 
Can you please pull the latest master? This issue you encountered was corrected with this commit

https://github.com/ElementsProject/elements/commit/eef2219389156e27144332c2a138f9f67bb44d19

**Comment by instagibbs** [comment]
feel free to squawk if it's not actually fixed
