### ISSUE TITLE
blindtrust option name is confusing, rename and invert meaning

### ISSUE THREAD

**Issue by wtogami** [ElementsProject/elements#81]
`blindtrust` is confusing.  It should be renamed and inverted to be clearer.

`blindtrust=1` is the default where it trusts incoming pegs without verifyiing against bitcoind.
`blindtrust=0` uses callrpc.cpp to query bitcoind when it needs to validate the incoming peg.

Rename the option and invert to default to `0`.
`validateincomingpeg` ?
`validatepeg` ?
`verifyincomingpeg` ?
`verifypeg` ?

Opinions?

**Comment by gwillen** [comment]
Agreed, I feel like this has caused communication problems in more than one case.

**Comment by instagibbs** [comment]
we renamed it a couple times.
