### ISSUE TITLE
issueasset creates P2PKH addresses, it would be better to issue to P2WPKH 

### ISSUE THREAD

**Issue by dgpv** [ElementsProject/elements#824]
`issueasset` uses `PKHash(newKey.GetID())`. It would be more convenient if it created segwit addresses, so that transactions that spend newly-created assets can have deterministic txid that won't change after signing the tx

https://github.com/ElementsProject/elements/blob/e5ab941489c564cd78845658b8e8688dc56817f5/src/wallet/rpcwallet.cpp#L6238-L6253

**Comment by instagibbs** [comment]
argh good catch. Ideally this output is chosen based on wallet defaults.

**Comment by instagibbs** [comment]
our hand will be forced with descriptor wallets by ~0.21

**Comment by stevenroose** [comment]
Closing this through #825. Gonna create a separate issue for using wallet default.
