### ISSUE TITLE
elements-qt: reduce custom transaction fee minimum to 100 sat/vKbyte

### ISSUE THREAD

**Issue by philippem** [ElementsProject/elements#832]
The elements-qt gui send dialog has a edit field for a custom transaction fee. In elements-0.18.1.5 it is not possible to drop the transaction fee below 1000 sat/vKbyte, without setting the  elements.conf  option `mintxfee=<amount>`. 

Given that elements will relay transactions with fees above 100 sat/vKbyte, it should be possible to choose lower fees.

The field will be reset to 1000 after entering a smaller number.

elements-qt 0.18.1.5

Linux Ubuntu 18.04.4 LTS
Gnome desktop

See attached screenshot.

**Comment by philippem** [comment]
<img width="667" alt="Screen Shot 2020-03-12 at 2 57 35 PM" src="https://user-images.githubusercontent.com/565792/76570120-e38d6d00-6471-11ea-9ffc-978b85936e47.png">

**Comment by instagibbs** [comment]
https://github.com/ElementsProject/elements/pull/833 should accomplish this.

QT allows it to be set lower, but not any lower than `0.00000100`, and remembers the last value you chose across restarts.

**Comment by instagibbs** [comment]
Hmm nevermind. Code as-is uses fee estimator to get minimum.

**Comment by stevenroose** [comment]
Hmm, that's strange. Is that a catch22? Because the fee estimator won't go lower than 1 sat/vb there won't be any txs lower than 1 sat/vb to make the estimator go lower than 1 sat/vb?

**Comment by instagibbs** [comment]
right, you don't want to ignore that because if mempool minfee raises somehow you don't want to not even enter the mempool.

**Comment by instagibbs** [comment]
Oh, I traced the code wrong. The slider actually goes lower when you set `-mintxfee=0.00000100`. It picks the max of min wallet fee rate and min relay rate. Works for me.

**Comment by stevenroose** [comment]
Is this solved in the latest release with the changed fee buckets? It's not 100% clear what the issue was exactly anymore. @philippem ?

**Comment by gwillen** [comment]
Just to confirm from my own testing: This appears to be fixed (minimum 100) in 0.18.1.7, and I verified that it displayed the old behavior (minimum 1000) in 0.18.1.5.

**Comment by stevenroose** [comment]
Closing then, if there's anything else, please reopen.
