### ISSUE TITLE
issuance blinding key vector size check in BlindTransaction: why num of issuances added ? 

### ISSUE THREAD

**Issue by dgpv** [ElementsProject/elements#842]
https://github.com/ElementsProject/elements/blob/ac5a435247b10b74fbaab9817ce7d199675b3d29/src/blind.cpp#L229-L230

Whenever `issuance_blinding_privkey` or `token_blinding_privkey` accessed, the index will be `< tx.vin.size()`, but the assert at the start of the function checks that the size of these vectors is less than `tx.vin.size()+GetNumIssuances(CTransaction(tx)`. Shouldn't it be just `tx.vin.size()`?

**Comment by stevenroose** [comment]
Hmm, good point. That's very old code.

I removed it in https://github.com/ElementsProject/elements/issues/842, I'm asking the people that originally wrote that code to review.

**Comment by dgpv** [comment]
#846 is merged, the issue is resolved
