### ISSUE TITLE
About tx fee not decreased much

### ISSUE THREAD

**Issue by uoso** [ElementsProject/elements#850]
I see latest release: https://github.com/ElementsProject/elements/releases/tag/elements-0.18.1.6 introduced decreased tx fees for the liquid transactions. However, after some tests, looks the fee does not drop much.
The fee is about 0.8688394276629572 sotoshi/vbytes now, just a little decreased from before(about 1sotoshi/vbytes).

The args used for rpc `sendtoaddress`  were:

- subtractfeefromamount: false
- replaceable: false
- conf_target: 1
- estimate_mode: ECONOMICAL

**Comment by allenpiscitello** [comment]
Not all of the functionaries have updated to support the lower fee, so your node is trying to estimate the chance to get in 1 block. Since transactions with lower fees will not make it into blocks created by functionaries with the upgrade, it will provide this estimate. 

As of writing this 14/15 have, so if you choose 2 block conf_target, you will likely see much lower fee estimates.

**Comment by uoso** [comment]
Hi, Thanks for your reply. I just tested with conf_target as 2 or 5, looks just a little difference with fee rate as about 0.8487 satoshi/vbyte. 

Is there a prefer which functionary will process my tx? 'cause looks all my tests gave me the similar results.

**Comment by uoso** [comment]
Just checked some piece of code, looks can set wallet fee-rate. so now I tested my tx fee rate could be 0.09988562714449103 satoshi/vbytes. So I have more questions now:

- Can it be lower than 0.1 satoshi/vbytes?
- Possible to set the fee rate per tx with method rpc `sendtoaddress`? Looks it can only estimate the fee with `conf_targets` and `estimmate_mode`.

**Comment by allenpiscitello** [comment]
Lower than 0.1 will not be relayed from standard nodes and won't be relayed to functionaries. 

There's no way to prefer which functionary - they are set based on the time of day (the functionary that has not been updated makes blocks at :03, :18, :33, :48 past each hour).

If you call settxfee, and set that to 0.000001, you should have the minimum fee set.

**Comment by uoso** [comment]
Ok, so probably liquid nodes think feerate  0.09988562714449103  as 0.1 sato/vB , see it got several confirmed.

**Comment by stevenroose** [comment]
We're also releasing a v0.18.1.7 version that improves fee estimation for low-fee values. Currently the estimation is kind-of biased against sub-satoshi feerates.

**Comment by stevenroose** [comment]
This is fixed in 0.18.1.7.
