### ISSUE TITLE
Replace Liquid Logo with Elements Logo in QT Application

### ISSUE THREAD

**Issue by allenpiscitello** [ElementsProject/elements#851]
We should use the Elements logo rather than the Liquid Logo in all places for consistency.

**Comment by stevenroose** [comment]
I recall we sometime decided to have Elements-Qt be Liquid branded. I don't know if it's possible to have the logo depended on the chain name. I'm not very fluent in the Qt code parts.

I'm quite indifferent for this all. I'm ok with using the Elements logo and the Elements brand more. I just had the impression we decided against that at some point.

**Comment by allenpiscitello** [comment]
The issue before was the Liquid/Elements branding was mismatched (some platforms one, some another, different if you build or not, etc...), so we decided it was much simpler to just go with the Elements branding for the application, but support Liquid as a default.

There is no need to change the logo based on chain, just always use Elements - it is much easier to just explain Elements is the software used to access Liquid.
