### ISSUE TITLE
Windows Setup installs into Bitcoin subfolder; icon says BitCoin Core

### ISSUE THREAD

**Issue by philippem** [ElementsProject/elements#868]
When installing from the win setup built using gitian on tag `elements-0.18.1.7-rc1` on a Windows 10 64 bit (MSEdge-Win10-VMware VM), the default install folder is "C:\Program Files(x86)\Bitcoin". Expected folder would be "C:\Program Files(x86)\Elements". In addition, the dialog displays "BitCoin Core". See attached screenshots.

![image](https://user-images.githubusercontent.com/565792/79622266-6d60d380-80cb-11ea-8ab7-cb0d6000b098.png)

**Comment by philippem** [comment]
This also happens with the win64-setup.

Setup files tested are `elements-0.18.1.7-win32-setup-unsigned.exe` and `elements-0.18.1.7-win64-setup-unsigned.exe`. 

![image](https://user-images.githubusercontent.com/565792/79622472-3f2fc380-80cc-11ea-9801-46f91a21ad17.png)

**Comment by stevenroose** [comment]
Yeah so grepping for `Program Files` gives no result, so I'll have to dig a bit deeper for where this string is actually defined :/

**Comment by dgpv** [comment]
https://github.com/ElementsProject/elements/blob/f0d97cdf70097de15a4aaf1321368a6a9f0f008a/share/setup.nsi.in#L53-L57

**Comment by stevenroose** [comment]
Clever grepping. I found it as well, grepping for "installer" IIRC :)
See https://github.com/ElementsProject/elements/pull/869. But thanks!
