### ISSUE TITLE
createpsbt output_assets parameter not working

### ISSUE THREAD

**Issue by asoltys** [ElementsProject/elements#875]
According to the docs for createpsbt, I should be able to provide a JSON object, "output_assets", as the fifth argument to the command to map outputs to assets as with createrawtransaction. But when I provide it, I get error code: -1 and the full createpsbt help text back as an error message.

This works with 4 arguments:

```
elements-cli createpsbt [] "[{\"AzpkXpbFsWC9aWJvah3JKg99zenqsGyYVhUuYWePmEK3LVozbf6by5wKRMXVKeZP34WzSJ5XwuKSukzM\": 0.05}]" 0 false
```

But as soon as I add the fifth argument, it doesn't:

```
elements-cli createpsbt [] "[{\"AzpkXpbFsWC9aWJvah3JKg99zenqsGyYVhUuYWePmEK3LVozbf6by5wKRMXVKeZP34WzSJ5XwuKSukzM\": 0.05}]" 0 false "{\"AzpkXpbFsWC9aWJvah3JKg99zenqsGyYVhUuYWePmEK3LVozbf6by5wKRMXVKeZP34WzSJ5XwuKSukzM\":\"b2e15d0d7a0c94e4e2ce0fe6e8691b9e451377f6e46e8045a86f7c4b5d4f0f23\"}"
```

I can try to investigate more, just raising the issue in the meantime.

**Comment by tiero** [comment]
@asoltys A possible workaround would be to call the `createrawatransaction` first and then pass to the the `converttopsbt` command the resulting hex string.

This is the only way AFAIK to create a PSET that spend an assets beside bitcoin.

**Comment by asoltys** [comment]
I think that's what I was attempting to do when I ran into #877

**Comment by apoelstra** [comment]
In #900 we overhauled the PSBT code and removed this parameter from `createpsbt`.
