### ISSUE TITLE
Question on fees

### ISSUE THREAD

**Issue by BlockMechanic** [ElementsProject/elements#890]
In Elements mode according to comments in code, only collects fees that match policyAsset, any particular reason miners cannot collect fess from ALL assets or is this WIP ?

**Comment by allenpiscitello** [comment]
Fees are designed to prevent spam. Since assets can be created without any underlying value, they do not necessarily prevent spam. If they did have value, block signers would have to be able to understand an exchange rate to effectively prioritize fees as well, which adds complexity.

**Comment by BlockMechanic** [comment]
Thanks, i will keep this in mind.
