### ISSUE TITLE
blindingdata entry in listtransactions should be removed

### ISSUE THREAD

**Issue by TheBlueMatt** [ElementsProject/elements#95]
The "blindingdata" entry added to mapValue looks very strange as its raw-binary instead of hex, and probably should just be skipped in JSON tx encodings entirely.

**Comment by sipa** [comment]
Agree, though the only easy way to do that would be to have a blacklist of
fields to not translate to json. Is that ok?

**Comment by Christewart** [comment]
Is 'blindingdata' necessary for other nodes? Isn't this only necessary for the person who will eventually claim the funds?

**Comment by sipa** [comment]
There is no need to export this information in its raw form over RPC. In
places where it's relevant it's added in human readable form.

The fact that it's exported at all is unintentional.

**Comment by instagibbs** [comment]
Excepted already.
