### ISSUE TITLE
OP_LSHIFT: MAX_SCRIPT_ELEMENT_SIZE

### ISSUE THREAD

**Issue by jl2012** [ElementsProject/elements#96]
https://github.com/ElementsProject/elements/blob/alpha/src/script/interpreter.cpp#L825

if (vch1.size() + full_bytes > MAX_SCRIPT_ELEMENT_SIZE)
should be:
if (vch1.size() + full_bytes + (bits > 0 ? 1 : 0) > MAX_SCRIPT_ELEMENT_SIZE)

Otherwise the result could be 1 byte larger than MAX_SCRIPT_ELEMENT_SIZE

**Comment by instagibbs** [comment]
Fixed at https://github.com/ElementsProject/elements/commit/6a3b75d257eeb9b4729e658821d3999430a5d5be#diff-be2905e2f5218ecdbe4e55637dac75f3R920 in `elements-0.13.1`
